/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import rsbuttom.CargarSplash;

import java.awt.Color;
import rojerusan.componentes.RSProgressBarSinText;
import rsbuttom.AWTUtilities;

/**
 *
 * @author Najera10
 */
public class splash extends javax.swing.JFrame {

    /**
     * Creates new form splash
     */
    public splash() {
        initComponents();
       AWTUtilities.setOpaque(this, rootPaneCheckingEnabled);
        this.setLocationRelativeTo(this);
        this.barraProgress.setValue(0);
        this.lblProgress.setText("0%");
        startThread();
        this.getContentPane().setBackground(Color.WHITE);
         this.setBackground(new Color(0,0,0,0));
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jEImagePanel1 = new LIB.JEImagePanel();
        barraProgress = new rojerusan.componentes.RSProgressBarSinText();
        lblProgress = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jEImagePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/splash.png"))); // NOI18N
        jEImagePanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barraProgress.setForeground(new java.awt.Color(0, 204, 246));
        barraProgress.setColorBorde(new java.awt.Color(0, 140, 160));
        barraProgress.setColorForeground(new java.awt.Color(0, 140, 160));
        jEImagePanel1.add(barraProgress, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 400, 30));

        lblProgress.setFont(new java.awt.Font("Segoe UI Light", 3, 24)); // NOI18N
        lblProgress.setForeground(new java.awt.Color(255, 255, 255));
        lblProgress.setText("50%");
        jEImagePanel1.add(lblProgress, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 80, -1));

        getContentPane().add(jEImagePanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new splash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.componentes.RSProgressBarSinText barraProgress;
    private LIB.JEImagePanel jEImagePanel1;
    private javax.swing.JLabel lblProgress;
    // End of variables declaration//GEN-END:variables
CargarSplash hilo;

public RSProgressBarSinText getProgress(){
    return this.barraProgress;
}

public void setProgress(RSProgressBarSinText progress){
    this.barraProgress = progress;
}
public void startThread(){
 hilo = new CargarSplash(getProgress(), this, lblProgress);
 hilo.start();
 hilo = null;
}

}
