/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modal;

import Alerts.Success;
import BD.Categorias;
import BD.CortedelDia;
import BD.configurarTicket;
import Controller.CCTicket;
import Controller.CCategorias;
import Controller.CCortedia;
import java.awt.Color;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import rsbuttom.AWTUtilities;

/**
 *
 * @author Najera10
 */
public class ConfigurarTicket extends javax.swing.JDialog {
  CortedelDia cortdd ; 
     Timer timer = null;
    TimerTask task;
    int i = 32;
      Categorias bdcat = new Categorias();
      CortedelDia corte = new CortedelDia();
    configurarTicket coft = new configurarTicket();

    public ConfigurarTicket(java.awt.Frame parent, boolean modal) {
            
        super(parent, modal);
        AWTUtilities.setOpaque(this, false);
        Ubicar(500);
        initComponents();
      CargarModeloTabla();
      lblid.hide();
        
    }
  
    public void CargarModeloTabla(){
      
       
       ArrayList<CCTicket>ListarDatos = coft.ObtenerDatos();
      int numerosUsusarios = ListarDatos.size();
      
        for (int i = 0; i < numerosUsusarios; i++) {
            CCTicket usuarios = ListarDatos.get(i);
            int idemp = usuarios.getIdempre();
            String nombre = usuarios.getNombre();
            String email = usuarios.getCorreo();
            String direccion = usuarios.getDireccion();
            String telefono = usuarios.getTelefono();
            String rfc = usuarios.getRfc();
            lblid.setText(""+idemp);
            txtnombre.setText(nombre);
            txtdireccion.setText(direccion);
            txtrelefono.setText(telefono);
            txtcorreo.setText(email);
            txtrfc.setText(rfc);

    
        }
    }
  

 
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblid = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnactualizar = new rojerusan.RSButtonMetro();
        txtnombre = new rojeru_san.RSMTextFull();
        txtdireccion = new rojeru_san.RSMTextFull();
        txtrelefono = new rojeru_san.RSMTextFull();
        txtrfc = new rojeru_san.RSMTextFull();
        txtcorreo = new rojeru_san.RSMTextFull();

        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel4.setText("Configurar Ticket");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 200, 60));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/icons8-multiplicar-50.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, 40));

        lblid.setText("jLabel6");
        jPanel1.add(lblid, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 60));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnactualizar.setText("Actualizar Ticket");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });
        jPanel2.add(btnactualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 290, 50));

        txtnombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnombre.setText("Nombre");
        txtnombre.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jPanel2.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, 310, 50));

        txtdireccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtdireccion.setText("Direccion");
        txtdireccion.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jPanel2.add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 310, 40));

        txtrelefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtrelefono.setText("Telefono");
        txtrelefono.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jPanel2.add(txtrelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 310, -1));

        txtrfc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtrfc.setText("Correo");
        txtrfc.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jPanel2.add(txtrfc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 310, -1));

        txtcorreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcorreo.setText("Correo");
        txtcorreo.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jPanel2.add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 310, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 310, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
          task = new TimerTask() {
            @Override
            public void run() {
                if (i == 0) {
                    Cerrar();
                } else {
                    Ubicar(i);
                    i -= 32;
                    Trasparencia((float) i / 352);
                }
            }
        };
        timer = new Timer();
        timer.schedule(task, 0, 2);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
  task = new TimerTask() {
            @Override
            public void run() {
                if (i == 352) {
                    timer.cancel();
                } else {
                    Ubicar(i);
                    i += 32;
                    Trasparencia((float) i / 352);
                }
            }
        };
        timer = new Timer();
        timer.schedule(task, 0, 2);        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
  setVisible(false);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed

        try {
            coft.actualizarTicket(lblid.getText(), txtnombre.getText(), txtdireccion.getText(), txtrelefono.getText(), txtrfc.getText(),txtrfc.getText());
        Success suc = new Success(new JFrame(),true );
        suc.titulos.setText("!HECHO¡");
        suc.textos.setText("SE HAN GUARDADO LOS CAMBIOS");
        suc.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(ConfigurarTicket.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnactualizarActionPerformed


    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfigurarTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfigurarTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfigurarTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfigurarTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 ConfigurarTicket dialog = new ConfigurarTicket(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonMetro btnactualizar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblid;
    private rojeru_san.RSMTextFull txtcorreo;
    private rojeru_san.RSMTextFull txtdireccion;
    private rojeru_san.RSMTextFull txtnombre;
    private rojeru_san.RSMTextFull txtrelefono;
    private rojeru_san.RSMTextFull txtrfc;
    // End of variables declaration//GEN-END:variables
private void Cerrar() {
        this.dispose();
        timer = null;
        task = null;
    }

    private void Trasparencia(float trasp) {
        AWTUtilities.setOpacity(this, trasp);
    }

    private void Ubicar(int y) {
        this.setLocation(590, y - 260);
    }   

}
