/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modal;

import Conexion.Conexion;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import principal.Principal;

/**
 *
 * @author Najera
 */
public class Respaldos extends javax.swing.JDialog {

     private Connection userConn;
    public Respaldos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(this);
    }

    
    
    public Respaldos(Connection conn) {
        this.userConn = conn;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(353, 228));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/descargar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 80, 70));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/subir-archivo.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 70, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         
            
         try {
             // add application code here
              Connection conn = DriverManager.
            getConnection("jdbc:h2:file:./base/PuntoVenta", "sa", "admin");
             conn.close();
             realizar_respaldo();
         } catch (SQLException ex) {
             Logger.getLogger(Respaldos.class.getName()).log(Level.SEVERE, null, ex);
         }
        
            
   

     
        
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         try {
             // add application code here
              Connection conn = DriverManager.
             getConnection("jdbc:h2:file:./base/PuntoVenta", "sa", "admin");
             conn.close();
             
             
             cargarRespaldo();
         } catch (SQLException ex) {
             Logger.getLogger(Respaldos.class.getName()).log(Level.SEVERE, null, ex);
         }
        
            
    }//GEN-LAST:event_jButton2ActionPerformed

    
   public void cargarRespaldo(){
       
       String path = System.getProperty("user.home")+"\\respaldos";    
      File directorio = new File(path);
      
      if(!directorio.exists()){
          JOptionPane.showMessageDialog(null,"no tiene respaldos");
         if (directorio.mkdirs()) {
             
             System.out.println("directorio creado");
         }else{
             System.out.println("error");
         }
      }else{
      JFileChooser file=new JFileChooser(path);
      file.showOpenDialog(file);
      File abre=file.getSelectedFile();
        
      String  fromFile  =  abre.toString();
      String toFile = "base/PuntoVenta.mv.db";
      
    boolean bandera =  cpy(fromFile,toFile);
    
    if(bandera){
        System.out.println("respaldo exitoso");
    }else{
        System.out.println("respaldo fallo");
    }
       
   }
   
   }
    
    
  public void realizar_respaldo(){
      
        Date date = new Date();
        
         SimpleDateFormat DateFor = new SimpleDateFormat("HH.mm.ss dd-MM-yyyy");
         String stringDate= DateFor.format(date);
         String path = System.getProperty("user.home");    
         File directorio = new File(path+"\\respaldos");
   
        String fromFile = "base/PuntoVenta.mv.db";
        String toFile = path+"\\respaldos\\PuntoVenta"+stringDate+".mv.db";
        
         
          
        if (!directorio.exists()) {
            if (directorio.mkdirs()) {
                System.out.println("Directorio creado");
           boolean   bandera = cpy(fromFile,toFile);
           
           if(bandera){
           
           JOptionPane.showMessageDialog(rootPane, "Respaldo  realizado !!");
    
           }else{
             JOptionPane.showMessageDialog(null, "Error con el respaldo", "", JOptionPane.ERROR_MESSAGE);
           }
            } else {
                System.out.println("Error al crear directorio");
            }
        }else{
            
            boolean   bandera = cpy(fromFile,toFile);
            if(bandera){
                
           JOptionPane.showMessageDialog(rootPane, "Respaldo  realizado !!");

            }else{
             JOptionPane.showMessageDialog(null, "Error con el respaldo", "", JOptionPane.WARNING_MESSAGE);

            }

        }
      
  }
    
     public boolean cpy(String fromFile, String toFile) {
        File origin = new File(fromFile);
        File destination = new File(toFile);
        if (origin.exists()) {
            try {
                InputStream in = new FileInputStream(origin);
                OutputStream out = new FileOutputStream(destination);
                // We use a buffer for the copy (Usamos un buffer para la copia).
                byte[] buf = new byte[1024];
                int len;
                while ((len = in.read(buf)) > 0) {
                    out.write(buf, 0, len);
                }
                in.close();
                out.close();
                return true;
            } catch (IOException ioe) {
                ioe.printStackTrace();
                return false;
            }
        } else {
            return false;
        }
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Respaldos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Respaldos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Respaldos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Respaldos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Respaldos dialog = new Respaldos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
