/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.UIManager;

public class pnlAlmacen extends javax.swing.JPanel {

    public static boolean click = false;
    /**
     * Creates new form pnlHome
     */
    public pnlAlmacen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorModulosAlmacen = new javax.swing.JDesktopPane(){
            ImageIcon icon = new ImageIcon(getClass().getResource("/img1/almacen.png"));
            Image image =icon.getImage();
            public void paintComponent(Graphics g){ g.drawImage(image,250,50,this);
            }
        };
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        fSButtonMD1 = new LIB.FSButtonMD();
        fSButtonMD2 = new LIB.FSButtonMD();
        rSButtonHover1 = new rojerusan.RSButtonHover();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1090, 634));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contenedorModulosAlmacen.setBackground(new java.awt.Color(244, 244, 244));

        javax.swing.GroupLayout contenedorModulosAlmacenLayout = new javax.swing.GroupLayout(contenedorModulosAlmacen);
        contenedorModulosAlmacen.setLayout(contenedorModulosAlmacenLayout);
        contenedorModulosAlmacenLayout.setHorizontalGroup(
            contenedorModulosAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
        );
        contenedorModulosAlmacenLayout.setVerticalGroup(
            contenedorModulosAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        add(contenedorModulosAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 54, 1100, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(128, 128, 131));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("ALMACEN");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 50));

        fSButtonMD1.setForeground(new java.awt.Color(0, 0, 0));
        fSButtonMD1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/list.png"))); // NOI18N
        fSButtonMD1.setText("Categorias");
        fSButtonMD1.setColorNormal(new java.awt.Color(144, 209, 0));
        fSButtonMD1.setColorPressed(new java.awt.Color(0, 204, 255));
        fSButtonMD1.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        fSButtonMD1.setPreferredSize(new java.awt.Dimension(200, 45));
        fSButtonMD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fSButtonMD1ActionPerformed(evt);
            }
        });
        jPanel1.add(fSButtonMD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, -1, 50));

        fSButtonMD2.setForeground(new java.awt.Color(0, 0, 0));
        fSButtonMD2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/product.png"))); // NOI18N
        fSButtonMD2.setText("Articulos");
        fSButtonMD2.setColorNormal(new java.awt.Color(255, 124, 31));
        fSButtonMD2.setColorPressed(new java.awt.Color(255, 153, 51));
        fSButtonMD2.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        fSButtonMD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fSButtonMD2ActionPerformed(evt);
            }
        });
        jPanel1.add(fSButtonMD2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, 50));

        rSButtonHover1.setBackground(new java.awt.Color(204, 255, 153));
        rSButtonHover1.setForeground(new java.awt.Color(0, 0, 0));
        rSButtonHover1.setText("Cancelacion Venta");
        rSButtonHover1.setColorHover(new java.awt.Color(0, 204, 0));
        rSButtonHover1.setColorText(new java.awt.Color(0, 0, 0));
        rSButtonHover1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rSButtonHover1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover1ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonHover1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, -1, 50));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 70));
    }// </editor-fold>//GEN-END:initComponents
pnlCategorias  pnlCategorias;
pnlProductos pnlArticulos;
pnlCancelacionVentas pnLCanC;
    private void fSButtonMD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fSButtonMD1ActionPerformed
   if(pnlCategorias == null){  
        pnlCategorias = new pnlCategorias();
            contenedorModulosAlmacen.add(pnlCategorias);
            contenedorModulosAlmacen.getDesktopManager().maximizeFrame(pnlCategorias);
            pnlCategorias.setVisible(true);
            

             }else{
           contenedorModulosAlmacen.getDesktopManager().maximizeFrame(pnlCategorias);
            
            

        }        // TODO add your handling code here:
    }//GEN-LAST:event_fSButtonMD1ActionPerformed

    private void fSButtonMD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fSButtonMD2ActionPerformed
        if(pnlArticulos == null){  
        pnlArticulos = new pnlProductos();
            contenedorModulosAlmacen.add(pnlArticulos);
            contenedorModulosAlmacen.getDesktopManager().maximizeFrame(pnlArticulos);
            pnlArticulos.setVisible(true);
            
            click = true;
            

             }else{
           contenedorModulosAlmacen.getDesktopManager().maximizeFrame(pnlArticulos);
            
            

        }   // TODO add your handling code here:
    }//GEN-LAST:event_fSButtonMD2ActionPerformed

    private void rSButtonHover1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover1ActionPerformed
if(pnLCanC == null){  
        pnLCanC = new pnlCancelacionVentas();
            contenedorModulosAlmacen.add(pnLCanC);
            contenedorModulosAlmacen.getDesktopManager().maximizeFrame(pnLCanC);
            pnLCanC.setVisible(true);
            

             }else{
           contenedorModulosAlmacen.getDesktopManager().maximizeFrame(pnLCanC);
            
            

        }   // TODO add your         // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonHover1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane contenedorModulosAlmacen;
    private LIB.FSButtonMD fSButtonMD1;
    private LIB.FSButtonMD fSButtonMD2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private rojerusan.RSButtonHover rSButtonHover1;
    // End of variables declaration//GEN-END:variables
}
