/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import Alerts.Information;
import Alerts.Success;
import Alerts.SuccessAlert;
import Alerts.Warning;
import Alerts.WarningAlert;
import BD.Categorias;
import Controller.CCategorias;
import java.awt.Frame;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import rojerusan.RSAnimation;

/**
 *
 * @author najera10
 */
public class pnlCategorias extends javax.swing.JInternalFrame {
    private TableRowSorter trsFiltro;
    public  String condicion; 
    
    
    DefaultTableModel modeloTablaCategorias = new DefaultTableModel(){
    public boolean isCellEditable(int filas, int columnas){
            if(columnas==3){
                return true;
            }else{
                return false;
            }
    }
    
    };
    Categorias bdcat = new Categorias();
   public CCategorias   catrgoriaselecionado = null ;
    public pnlCategorias() {
        initComponents();
        CargarColunmas();
        CargarModeloTabla();
      
    }
    
        private  void CargarColunmas(){
        modeloTablaCategorias.addColumn("Nombre");
        modeloTablaCategorias.addColumn("Descripcion");
        modeloTablaCategorias.addColumn("Condicion");
        
    }

        public void CargarModeloTabla(){
      
    limpiarTabla();
       ArrayList<CCategorias>ListarCategorias = bdcat.ObtenerCategorias();
      int numerosProveedpres = ListarCategorias.size();
      modeloTablaCategorias.setNumRows(numerosProveedpres);
        for (int i = 0; i < numerosProveedpres; i++) {
            CCategorias categoria = ListarCategorias.get(i);
            String nombre = categoria.getNombre();
            String descripcion = categoria.getDescripcion();
            int condicion = categoria.getEstado();
            String estado = "";        
            if (condicion == 1){
                        estado = "Activo";
                    }else{
                        estado = "Inactivo";
                    }  
            
            modeloTablaCategorias.setValueAt(categoria, i, 0);
            modeloTablaCategorias.setValueAt(descripcion, i, 1);
            modeloTablaCategorias.setValueAt(estado, i, 2);
            
        }
         
    }
//    public void filtroBusqueda(JTextField txt) {
//        trsFiltro.setRowFilter(RowFilter.regexFilter(txt.getText()));
//    }
//
//   
    public void filtroBusqueda(JTextField txt) {
        trsFiltro.setRowFilter(RowFilter.regexFilter(txt.getText()));
    }
    
    public void limpiar(){
        txtnombre.setText("");
        txtdescripcion.setText("");
         }
        public  void limpiarTabla(){
        int numFilas = modeloTablaCategorias.getRowCount();
        if(numFilas > 0){
            for(int i = numFilas - 1; i >= 0; i--){
                modeloTablaCategorias.removeRow(i);
            }
        }
    }
        
  
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCategorias = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pnlcategorias = new LIB.JPanelRound();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fSButtonMD1 = new LIB.FSButtonMD();
        fSButtonMD2 = new LIB.FSButtonMD();
        fSButtonMD3 = new LIB.FSButtonMD();
        txtnombre = new rojerusan.RSMetroTextFullPlaceHolder();
        txtdescripcion = new rojeru_san.rsfield.RSTextFull();
        txtbuscarcategoria = new rojeru_san.rsfield.RSTextFull();

        setPreferredSize(new java.awt.Dimension(900, 429));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(128, 128, 131));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/maintenance_1.png"))); // NOI18N
        jLabel7.setText("Categorias");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 460, 100));

        tablaCategorias.setModel(modeloTablaCategorias);
        tablaCategorias.setRowHeight(25);
        tablaCategorias.setRowMargin(0);
        tablaCategorias.setSelectionBackground(new java.awt.Color(102, 153, 255));
        tablaCategorias.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaCategorias.getSelectionModel().addListSelectionListener(
            new ListSelectionListener(){
                public void valueChanged(ListSelectionEvent event){
                    if(!event.getValueIsAdjusting() && (tablaCategorias.getSelectedRow()>= 0) ){
                        int filaseleccionada = tablaCategorias.getSelectedRow();
                        CCategorias categoria = (CCategorias) modeloTablaCategorias.getValueAt(filaseleccionada, 0);
                        txtnombre.setText(categoria.getNombre());
                        txtdescripcion.setText(categoria.getDescripcion());

                        catrgoriaselecionado = categoria;

                    }
                }
            }
        );
        jScrollPane1.setViewportView(tablaCategorias);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 1040, 210));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Listado de Categorias");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 240, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Buscar:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, 30));

        pnlcategorias.setBackground(new java.awt.Color(255, 255, 255));
        pnlcategorias.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        pnlcategorias.setColorPrimario(new java.awt.Color(255, 255, 255));
        pnlcategorias.setColorSecundario(new java.awt.Color(255, 255, 255));
        pnlcategorias.setOpaque(true);
        pnlcategorias.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Nombre *");
        pnlcategorias.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 90, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Descripcion*");
        pnlcategorias.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        fSButtonMD1.setBackground(new java.awt.Color(102, 166, 54));
        fSButtonMD1.setForeground(new java.awt.Color(0, 0, 0));
        fSButtonMD1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/diskette.png"))); // NOI18N
        fSButtonMD1.setMnemonic('g');
        fSButtonMD1.setText("Guardar");
        fSButtonMD1.setToolTipText("");
        fSButtonMD1.setColorHover(new java.awt.Color(204, 255, 102));
        fSButtonMD1.setColorNormal(new java.awt.Color(102, 166, 54));
        fSButtonMD1.setColorPressed(new java.awt.Color(102, 166, 54));
        fSButtonMD1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fSButtonMD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fSButtonMD1ActionPerformed(evt);
            }
        });
        pnlcategorias.add(fSButtonMD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 130, -1));

        fSButtonMD2.setBackground(new java.awt.Color(81, 161, 194));
        fSButtonMD2.setForeground(new java.awt.Color(0, 0, 0));
        fSButtonMD2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/brush.png"))); // NOI18N
        fSButtonMD2.setMnemonic('c');
        fSButtonMD2.setText("Limpiar");
        fSButtonMD2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fSButtonMD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fSButtonMD2ActionPerformed(evt);
            }
        });
        pnlcategorias.add(fSButtonMD2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 130, -1));

        fSButtonMD3.setBackground(new java.awt.Color(255, 102, 51));
        fSButtonMD3.setForeground(new java.awt.Color(0, 0, 0));
        fSButtonMD3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/garbage.png"))); // NOI18N
        fSButtonMD3.setMnemonic('e');
        fSButtonMD3.setText("Eliminar");
        fSButtonMD3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fSButtonMD3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fSButtonMD3ActionPerformed(evt);
            }
        });
        pnlcategorias.add(fSButtonMD3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 130, -1));

        txtnombre.setForeground(new java.awt.Color(0, 0, 0));
        txtnombre.setActionCommand("<Not Set>");
        txtnombre.setBorderColor(new java.awt.Color(153, 153, 255));
        txtnombre.setBotonColor(new java.awt.Color(255, 102, 102));
        txtnombre.setMayusculas(true);
        txtnombre.setPhColor(new java.awt.Color(0, 0, 0));
        txtnombre.setPlaceholder("Categoria");
        pnlcategorias.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        txtdescripcion.setForeground(new java.awt.Color(0, 0, 0));
        txtdescripcion.setBordeColorFocus(new java.awt.Color(153, 153, 255));
        txtdescripcion.setBotonColor(new java.awt.Color(255, 102, 102));
        txtdescripcion.setMayusculas(true);
        txtdescripcion.setPlaceholder("Descripcion");
        txtdescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdescripcionActionPerformed(evt);
            }
        });
        pnlcategorias.add(txtdescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 420, -1));

        jPanel2.add(pnlcategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 460, 280));

        txtbuscarcategoria.setMayusculas(true);
        txtbuscarcategoria.setPlaceholder("Buscar");
        txtbuscarcategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarcategoriaKeyReleased(evt);
            }
        });
        jPanel2.add(txtbuscarcategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fSButtonMD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fSButtonMD1ActionPerformed
  try {
            String nombre = txtnombre.getText();
            String descripcion = txtdescripcion.getText();
            
            if (nombre.equals("") || descripcion.equals("")) {
            
                //JOptionPane.showMessageDialog(null, "Verifique los datos");
            WarningAlert w = new WarningAlert(new JFrame(), true);
            w.msj1.setText("ALGO PASO");
            w.msj2.setText("VERIFIQUE SUS DATOS");
            w.msj3.setText("");
            w.setVisible(true);
            }else{
                
        int cuentaFilasSeleccionadas = tablaCategorias.getSelectedRowCount();
        if (cuentaFilasSeleccionadas == 1) {
            bdcat.actualizarCategoria(catrgoriaselecionado, nombre, descripcion);
            CargarModeloTabla();
             limpiar();
                       SuccessAlert suc = new SuccessAlert(new JFrame(),true );
                       suc.msj1.setText("!HECHO¡");
                       suc.msj2.setText("SE HAN ACTUALIZADO LOS DATOS");
                       suc.msj3.setText("");
                       suc.setVisible(true);
            
        }else if(cuentaFilasSeleccionadas == 0){
            CCategorias cate = new CCategorias("0",nombre,descripcion,1);
           int  actulizar =  bdcat.insert(cate);
             CargarModeloTabla();
            limpiar();
           if(actulizar >=1){
                 SuccessAlert suc = new SuccessAlert(new JFrame(),true );
                       suc.msj1.setText("!HECHO¡");
                       suc.msj2.setText("SE HAN GUARDADO LOS CAMBIOS");
                       suc.msj3.setText("");
                       suc.setVisible(true);
           } 
         
        
        }
            }
        } catch (SQLException ex) {
            Logger.getLogger(pnlCategorias.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_fSButtonMD1ActionPerformed

    private void fSButtonMD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fSButtonMD2ActionPerformed
limpiar();
tablaCategorias.clearSelection ();        // TODO add your handling code here:
    }//GEN-LAST:event_fSButtonMD2ActionPerformed

    private void fSButtonMD3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fSButtonMD3ActionPerformed
      try{
        int cuentaFilasSeleccionadas = tablaCategorias.getSelectedRowCount();
            if (cuentaFilasSeleccionadas == 0) {
               // JOptionPane.showMessageDialog(null, "Debe serleccionar alguna fila");
            //new RSNotifyFade("!Alerta!", "Debe serleccionar alguna fila", 7, RSNotifyFade.PositionNotify.TopLef, RSNotifyFade.TypeNotify.WARNING).setVisible(true);
            WarningAlert w = new WarningAlert(new JFrame(), true);
            w.msj1.setText("ALGO OCURRIO ");
            w.msj2.setText("DEBE SELECCIONAR UNA FILA..");
            w.msj3.setText("");
            w.setVisible(true);
            }else{
                WarningAlert w = new WarningAlert(new JFrame(), true);
                w.msj1.setText("ESTAS SEGURO°°°");
                w.msj2.setText("¡DESEAS ELIMINARLO?");
                w.msj3.setText("");
                w.setVisible(true);
                      
                 if (w.hecho) {
                bdcat.eliminarCatedoria(catrgoriaselecionado);
                //JOptionPane.showMessageDialog(null, "Categoria  eliminada");
            //new RSNotifyFade("!Alerta!", "Categoria eliminada", 7, RSNotifyFade.PositionNotify.TopLef, RSNotifyFade.TypeNotify.ERROR).setVisible(true);
                limpiar();
                CargarModeloTabla();
          
        }
                SuccessAlert succ  = new SuccessAlert(new Frame(), true);
                succ.msj1.setText("CORRECTO !!!");
                succ.msj2.setText("SE HA ELIMINADO");
                succ.msj3.setText("");
                succ.setVisible(true);
        }
            
          
        } catch (SQLException ex) {
            Logger.getLogger(pnlUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_fSButtonMD3ActionPerformed

    private void txtdescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdescripcionActionPerformed

    private void txtbuscarcategoriaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarcategoriaKeyReleased
     limpiarTabla();    
    String cadena  = txtbuscarcategoria.getText();
    
    ArrayList<CCategorias> ListarCategorias = bdcat.ObtenerCategoriasporCriterio(cadena);
    int numeroCategorias = ListarCategorias.size();
    modeloTablaCategorias.setNumRows(numeroCategorias);
    
        for (int i = 0; i < numeroCategorias; i++) {
            CCategorias categoria = ListarCategorias.get(i);
            String nombre = categoria.getNombre();
            String descripcion = categoria.getDescripcion();
            int condicion = categoria.getEstado();
            String estado = "";        
            if (condicion == 1){
                        estado = "Activo";
                    }else{
                        estado = "Inactivo";
                    }  
            
            modeloTablaCategorias.setValueAt(categoria, i, 0);
            modeloTablaCategorias.setValueAt(descripcion, i, 1);
            modeloTablaCategorias.setValueAt(estado, i, 2);
            
        }   // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarcategoriaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private LIB.FSButtonMD fSButtonMD1;
    private LIB.FSButtonMD fSButtonMD2;
    private LIB.FSButtonMD fSButtonMD3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private LIB.JPanelRound pnlcategorias;
    public static javax.swing.JTable tablaCategorias;
    private rojeru_san.rsfield.RSTextFull txtbuscarcategoria;
    private rojeru_san.rsfield.RSTextFull txtdescripcion;
    private rojerusan.RSMetroTextFullPlaceHolder txtnombre;
    // End of variables declaration//GEN-END:variables
}
