/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import Alerts.ErrorAlert;
import Alerts.SuccessAlert;
import Alerts.WarningAlert;
import BD.Ingreso;
import BD.Producto;
import Controller.CDetalle_ingresos;
import Controller.CIngreso;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author Najera
 */
public class pnlCancelacionCompra extends javax.swing.JInternalFrame {

    /**
     * Creates new form pnlCancelacionCompra
     */
    Ingreso ing = new Ingreso();
    Producto prod = new Producto();
    
       DefaultTableModel modeloTablaIngresos = new DefaultTableModel(){
    
      public boolean isCellEditable(int filas, int columnas){
            if(columnas == 4){
                return true;
            }else{
                return false;
            }
    }
    
    };   
    private TableRowSorter trsFiltro;
    public pnlCancelacionCompra() {
        initComponents();
         modeloTablaIngresos.addColumn("Folio");
        modeloTablaIngresos.addColumn("Total");
        modeloTablaIngresos.addColumn("Fecha");
        modeloTablaIngresos.addColumn("Estatus");
        
        tblIngresos.setModel(modeloTablaIngresos);
       
        CargarModeloTabla();
        addEventKey();
                
    }

    private void addEventKey(){
           KeyStroke f1 = KeyStroke.getKeyStroke(KeyEvent.VK_F1, 0, false);
        Action f1Action = new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                
                txtbuscar.requestFocus();
                
            }
        };  
        
        this.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(f1, "F1");
        this.getActionMap().put("F1", f1Action);
    }
    public void CargarModeloTabla(){
        
        
       ArrayList<CIngreso>ListarIngresos = ing.ObtenerIngresos();
      int numeroIngresos = ListarIngresos.size();
      modeloTablaIngresos.setNumRows(numeroIngresos);
        for (int i = 0; i < numeroIngresos; i++) {
            CIngreso ingresos = ListarIngresos.get(i);
            int id = ingresos.getIdingreso();
            Double total = ingresos.getTotal_compra();
            String fecha = String.valueOf(ingresos.getFecha_hora());
            String estatus = ingresos.getEstado();
            
           
            modeloTablaIngresos.setValueAt(id, i, 0);
            modeloTablaIngresos.setValueAt(total, i, 1);
            modeloTablaIngresos.setValueAt(fecha, i, 2);
            modeloTablaIngresos.setValueAt(estatus, i, 3);
        }
         
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblIngresos = new rojerusan.RSTableMetro();
        txtbuscar = new rojerusan.RSMetroTextFullPlaceHolder();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblIngresos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Folio", "Total", "Fecha", "Estado"
            }
        ));
        tblIngresos.setColorBackgoundHead(new java.awt.Color(204, 204, 255));
        tblIngresos.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        tblIngresos.setColorFilasBackgound2(new java.awt.Color(204, 255, 255));
        tblIngresos.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tblIngresos.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tblIngresos.setColorForegroundHead(new java.awt.Color(0, 0, 0));
        tblIngresos.setColorSelBackgound(new java.awt.Color(255, 102, 102));
        tblIngresos.setColorSelForeground(new java.awt.Color(51, 51, 51));
        tblIngresos.setFuenteFilas(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tblIngresos.setFuenteFilasSelect(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tblIngresos.setFuenteHead(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tblIngresos.setMultipleSeleccion(false);
        tblIngresos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblIngresosKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblIngresosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblIngresos);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1100, 480));

        txtbuscar.setBorderColor(new java.awt.Color(204, 204, 255));
        txtbuscar.setPlaceholder("Busca  la Compra ....");
        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarKeyReleased(evt);
            }
        });
        jPanel2.add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 430, -1));

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyReleased
 txtbuscar.addKeyListener(new KeyAdapter() {
            public void keyReleased(final KeyEvent e) {
                String cadena = (txtbuscar.getText());
                txtbuscar.setText(cadena);
                repaint();
                filtroBusqueda(txtbuscar);
            }
        });
        trsFiltro = new TableRowSorter(tblIngresos.getModel());
        tblIngresos.setRowSorter(trsFiltro);             // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarKeyReleased

    private void tblIngresosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblIngresosKeyPressed
 
    }//GEN-LAST:event_tblIngresosKeyPressed

    private void tblIngresosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblIngresosKeyReleased
         if(evt.getKeyCode()==KeyEvent.VK_ESCAPE){
             int seleccionaopcion = tblIngresos.getSelectedRow();
             if(seleccionaopcion < 0){
                 System.out.println("no hay");
             }else{
                 
                  String estatus=String.valueOf(modeloTablaIngresos.getValueAt(seleccionaopcion,3));

                      if(estatus.equals("Cancelada")){
                       ErrorAlert e= new ErrorAlert(new JFrame(), true);
                        e.msj1.setText("ESTA VENTA YA ESTA CANCELADA");
                        e.msj2.setText("");
                        e.msj3.setText("");
                        e.setVisible(true);
                          
                      }else{
                 try {
                    
                       WarningAlert w = new WarningAlert(new JFrame(), true);
                        w.msj1.setText("ESTAS SEGURO°°°");
                        w.msj2.setText("¡DESEAS CANCELAR EL INGRESO?");
                        w.msj3.setText("todos los productos se descontaran");
                        w.setVisible(true);

                        if (w.hecho) {
                     String id=String.valueOf(modeloTablaIngresos.getValueAt(seleccionaopcion,0));
                     obtenerDetalles(id);
//                     ing.eliminarDetalleIngresos(id);
                     borrar(id);
                         SuccessAlert succ  = new SuccessAlert(new Frame(), true);
                succ.msj1.setText("CORRECTO !!!");
                succ.msj2.setText("SE HA CANCELADO");
                succ.msj3.setText("");
                succ.setVisible(true);
                CargarModeloTabla();
                        }
            
                 } catch (SQLException ex) {
                     Logger.getLogger(pnlCancelacionCompra.class.getName()).log(Level.SEVERE, null, ex);
                 }
               }
             
             }

         }
    }//GEN-LAST:event_tblIngresosKeyReleased
 public void filtroBusqueda(JTextField txt) {
        trsFiltro.setRowFilter(RowFilter.regexFilter(txt.getText()));
    }
 
 
 public void borrar(String id){
        try {
            
            ing.eliminarIngresos(id);
        } catch (SQLException ex) {
            Logger.getLogger(pnlCancelacionCompra.class.getName()).log(Level.SEVERE, null, ex);
        }
 }
 
 public void  obtenerDetalles(String id) throws SQLException{
     
     
      ArrayList<CDetalle_ingresos>ListarUsuarios = ing.obtenerDetalles(id);
      int numerosUsusarios = ListarUsuarios.size();
     
        for (int i = 0; i < numerosUsusarios; i++) {
                
           CDetalle_ingresos ingresos = ListarUsuarios.get(i);
           String articulo = String.valueOf(ingresos.getIdarticulo());
           ArrayList<Double> Stocks =  prod.Obtener_stock(articulo);
                for (int j = 0; j < Stocks.size(); j++) {
                    String cadena = Stocks.get(j).toString();
                    double stockingreso = ingresos.getCantidad();
                    double stockreal =Double.parseDouble(Stocks.get(j).toString());
                    double resultado = stockreal - stockingreso;
                    prod.Rest_Stock(articulo, resultado);
                }
            
        }
 
 }

 
 
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private rojerusan.RSTableMetro tblIngresos;
    private rojerusan.RSMetroTextFullPlaceHolder txtbuscar;
    // End of variables declaration//GEN-END:variables
}
