/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import Alerts.ErrorAlert;
import Alerts.SuccessAlert;
import Alerts.WarningAlert;
import BD.Producto;
import BD.Venta;
import Controller.CDetalle_ventas;
import Controller.CVenta;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Najera
 */
public class pnlCancelacionVentas extends javax.swing.JInternalFrame {
  DefaultTableModel modeloTablaVentas = new DefaultTableModel(){
    
      public boolean isCellEditable(int filas, int columnas){
            if(columnas == 4){
                return true;
            }else{
                return false;
            }
    }
    
    };  
        Venta ven = new Venta();
        Producto prod = new Producto();
    public pnlCancelacionVentas() {
        initComponents();
        modeloTablaVentas.addColumn("Codigo");
        modeloTablaVentas.addColumn("Total");
        modeloTablaVentas.addColumn("Fecha");
        modeloTablaVentas.addColumn("Estatus");
        
        tblventas.setModel(modeloTablaVentas);
        CargarModeloTabla();
        addEventKey();
    }
    
      private void addEventKey(){
           KeyStroke f1 = KeyStroke.getKeyStroke(KeyEvent.VK_F1, 0, false);
        Action f1Action = new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                
                txtbuscar.requestFocus();
                
            }
        };  
        
        this.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(f1, "F1");
        this.getActionMap().put("F1", f1Action);
    }

      
        public void CargarModeloTabla(){
       
      ArrayList<CVenta>ListarVentas= ven.ObtenerVentas();
      int numeroVentas = ListarVentas.size();
      modeloTablaVentas.setNumRows(numeroVentas);
        for (int i = 0; i < numeroVentas; i++) {
            CVenta ventas = ListarVentas.get(i);
            int id = ventas.getIdVenta();
            Double total = ventas.getMontoVenta();
            String fecha = String.valueOf(ventas.getFecha_hora());
            String estatus = ventas.getEstado();
            
           
            modeloTablaVentas.setValueAt(id, i, 0);
            modeloTablaVentas.setValueAt(total, i, 1);
            modeloTablaVentas.setValueAt(fecha, i, 2);
            modeloTablaVentas.setValueAt(estatus, i, 3);
        }
         
    }
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblventas = new rojerusan.RSTableMetro();
        txtbuscar = new rojerusan.RSMetroTextFullPlaceHolder();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblventas.setColorBackgoundHead(new java.awt.Color(204, 204, 255));
        tblventas.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        tblventas.setColorBordeHead(new java.awt.Color(255, 255, 255));
        tblventas.setColorFilasBackgound2(new java.awt.Color(204, 255, 255));
        tblventas.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tblventas.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tblventas.setColorForegroundHead(new java.awt.Color(0, 0, 0));
        tblventas.setColorSelBackgound(new java.awt.Color(255, 102, 102));
        tblventas.setColorSelForeground(new java.awt.Color(51, 51, 51));
        tblventas.setGridColor(new java.awt.Color(204, 204, 204));
        tblventas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblventasKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblventas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 960, 420));

        txtbuscar.setBorderColor(new java.awt.Color(153, 153, 255));
        txtbuscar.setPlaceholder("Busca  la Compra ....");
        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarKeyReleased(evt);
            }
        });
        jPanel1.add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 430, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 985, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyReleased
        txtbuscar.addKeyListener(new KeyAdapter() {
            public void keyReleased(final KeyEvent e) {
                String cadena = (txtbuscar.getText());
                txtbuscar.setText(cadena);
                repaint();
//                filtroBusqueda(txtbuscar);
            }
        });
//        trsFiltro = new TableRowSorter(tblIngresos.getModel());
//        tblIngresos.setRowSorter(trsFiltro);             // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarKeyReleased

    private void tblventasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblventasKeyReleased
if(evt.getKeyCode()==KeyEvent.VK_ESCAPE){
             int seleccionaopcion = tblventas.getSelectedRow();
             if(seleccionaopcion < 0){
                 System.out.println("no hay");
             }else{
             String estatus=String.valueOf(modeloTablaVentas.getValueAt(seleccionaopcion,3));

                      if(estatus.equals("Cancelada")){
                          
                          ErrorAlert e= new ErrorAlert(new JFrame(), true);
                        e.msj1.setText("ESTA VENTA YA ESTA CANCELADA");
                        e.msj2.setText("");
                        e.msj3.setText("");
                        e.setVisible(true);
                          
                      }else{
                          
                      
                 try {
                    
                       WarningAlert w = new WarningAlert(new JFrame(), true);
                        w.msj1.setText("ESTAS SEGURO°°°");
                        w.msj2.setText("¡DESEAS CANCELAR EL INGRESO?");
                        w.msj3.setText("todos los productos se descontaran");
                        w.setVisible(true);

                        if (w.hecho) {
                       String id=String.valueOf(modeloTablaVentas.getValueAt(seleccionaopcion,0));
                            obtenerDetalles(id);
                            ActualizarStatus(id);
                        }
                SuccessAlert succ  = new SuccessAlert(new Frame(), true);
                succ.msj1.setText("CORRECTO !!!");
                succ.msj2.setText("SE HA CANCELADO");
                succ.msj3.setText("");
                succ.setVisible(true);
                CargarModeloTabla();
                 } catch (SQLException ex) {
                     Logger.getLogger(pnlCancelacionCompra.class.getName()).log(Level.SEVERE, null, ex);
                 }
                }
             }

         }        // TODO add your handling code here:
    }//GEN-LAST:event_tblventasKeyReleased

     
 public void ActualizarStatus(String id){
        try {
            
            ven.eliminarVenta(id);
        } catch (SQLException ex) {
            Logger.getLogger(pnlCancelacionCompra.class.getName()).log(Level.SEVERE, null, ex);
        }
 }
 
 public void  obtenerDetalles(String id) throws SQLException{
     
     
      ArrayList<CDetalle_ventas>ListarVentas = ven.obtenerDetalles(id);
      int numerosVentas = ListarVentas.size();
     
        for (int i = 0; i < numerosVentas; i++) {
                
           CDetalle_ventas ventas = ListarVentas.get(i);
           String articulo = String.valueOf(ventas.getIdProd());
           ArrayList<Double> Stocks =  prod.Obtener_stock(articulo);
                for (int j = 0; j < Stocks.size(); j++) {
                    String cadena = Stocks.get(j).toString();
                    double stockventa = ventas.getCantidadVendida();
                    double stockreal =Double.parseDouble(Stocks.get(j).toString());
                    double resultado = stockreal + stockventa;
                    prod.Rest_Stock(articulo, resultado);
                }
            
        }
 
 }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private rojerusan.RSTableMetro tblventas;
    private rojerusan.RSMetroTextFullPlaceHolder txtbuscar;
    // End of variables declaration//GEN-END:variables
}
