/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import Alerts.Information;
import Alerts.Success;
import Alerts.Warning;
import BD.Proveedores;
import Controller.CProveedores;
import Controller.CUsuarios;
import java.awt.Frame;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author najera10
 */
public class pnlproveedores extends javax.swing.JInternalFrame {
    private TableRowSorter trsFiltro;
     
DefaultTableModel modelotablaProveedores = new DefaultTableModel(){

  public boolean isCellEditable(int filas, int columnas){
            if(columnas==4){
                return true;
            }else{
                return false;
            }
    }


};
Proveedores  bdprv = new Proveedores();
CProveedores  proveedorselecionado = null ;

    public pnlproveedores() {
        initComponents();
        CargarColunmas();
        CargarModeloTabla();
    }
    
        private  void CargarColunmas(){
        modelotablaProveedores.addColumn("Nombre");
        modelotablaProveedores.addColumn("Dirección");
        modelotablaProveedores.addColumn("Telefono");
        modelotablaProveedores.addColumn("Email");
    }

    public void CargarModeloTabla(){
      
       limpiarTabla();
       ArrayList<CProveedores>ListarProveedores = bdprv.ObtenerProveedores();
      int numerosProveedpres = ListarProveedores.size();
      modelotablaProveedores.setNumRows(numerosProveedpres);
        for (int i = 0; i < numerosProveedpres; i++) {
            CProveedores proveedor = ListarProveedores.get(i);
            String nombre = proveedor.getNombre();
            String email = proveedor.getEmail();
            String direccion = proveedor.getDireccion();
            String telefono = proveedor.getTelefono();        
            modelotablaProveedores.setValueAt(proveedor, i, 0);
            modelotablaProveedores.setValueAt(direccion, i, 1);
            modelotablaProveedores.setValueAt(telefono, i, 2);
            modelotablaProveedores.setValueAt(email, i, 3);
        }
         
    }
    
 public void filtroBusqueda(JTextField txt) {
        trsFiltro.setRowFilter(RowFilter.regexFilter(txt.getText()));
 }

    public void limpiar(){
        txtnombre.setText("");
        txtdireccion.setText("");
        txttelefono.setText("");
        txtemail.setText("");
    }
        public  void limpiarTabla(){
        int numFilas = modelotablaProveedores.getRowCount();
        if(numFilas > 0){
            for(int i = numFilas - 1; i >= 0; i--){
                modelotablaProveedores.removeRow(i);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bUSCAR = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProveedores = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtbusqueda = new javax.swing.JTextField();
        jPanelRound1 = new LIB.JPanelRound();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txttelefono = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnagregar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bUSCAR.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bUSCAR.setText("Buscar:");
        jPanel1.add(bUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 50, 30));

        tablaProveedores.setModel(modelotablaProveedores);
        tablaProveedores.setRowHeight(25);
        tablaProveedores.setRowMargin(0);
        tablaProveedores.setSelectionBackground(new java.awt.Color(102, 153, 255));
        tablaProveedores.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaProveedores.getSelectionModel().addListSelectionListener(
            new ListSelectionListener(){
                public void valueChanged(ListSelectionEvent event){
                    if(!event.getValueIsAdjusting() && (tablaProveedores.getSelectedRow()>= 0) ){
                        int filaseleccionada = tablaProveedores.getSelectedRow();
                        CProveedores proveedor = (CProveedores) modelotablaProveedores.getValueAt(filaseleccionada, 0);
                        txtnombre.setText(proveedor.getNombre());
                        txtdireccion.setText(proveedor.getDireccion());
                        txtemail.setText(proveedor.getEmail());
                        txttelefono.setText(proveedor.getTelefono());
                        proveedorselecionado = proveedor;

                    }
                }
            }   
        );
        jScrollPane1.setViewportView(tablaProveedores);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 1070, 230));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(128, 128, 131));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/fundraiser.png"))); // NOI18N
        jLabel7.setText("PROVEEDORES");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 520, 110));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Listado de Proveedores");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 210, -1));

        txtbusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbusquedaKeyTyped(evt);
            }
        });
        jPanel1.add(txtbusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 150, 30));

        jPanelRound1.setBackground(new java.awt.Color(255, 255, 255));
        jPanelRound1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        jPanelRound1.setOpaque(true);
        jPanelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Registro de Proveedor");
        jPanelRound1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 210, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Nombre *");
        jPanelRound1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        txtnombre.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtnombre.setForeground(new java.awt.Color(102, 153, 255));
        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        jPanelRound1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 180, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Direccion*");
        jPanelRound1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        txtdireccion.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jPanelRound1.add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 180, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Telenono *");
        jPanelRound1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 70, -1));

        txttelefono.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jPanelRound1.add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 180, -1));

        txtemail.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jPanelRound1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 180, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Email *");
        jPanelRound1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 50, 30));

        btnagregar.setBackground(new java.awt.Color(102, 166, 54));
        btnagregar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/diskette.png"))); // NOI18N
        btnagregar.setMnemonic('g');
        btnagregar.setText("Agregar");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });
        jPanelRound1.add(btnagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 120, 40));

        btneliminar.setBackground(new java.awt.Color(247, 94, 24));
        btneliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/garbage.png"))); // NOI18N
        btneliminar.setMnemonic('e');
        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        jPanelRound1.add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 110, 40));

        jButton1.setBackground(new java.awt.Color(81, 161, 194));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/brush.png"))); // NOI18N
        jButton1.setMnemonic('c');
        jButton1.setText("limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelRound1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 120, 40));

        jPanel1.add(jPanelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 290, 320));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1090, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
    try {
        String nombre = txtnombre.getText();
        String telefono = txttelefono.getText();
        String email = txtemail.getText();
        String  direccion = txtdireccion.getText(); 
        Pattern pattern = Pattern
                .compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                        + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
        Matcher mather = pattern.matcher(email);
        if (nombre.equals("") || telefono.equals("") || email.equals("") || direccion.equals("")){
            Information info  = new Information(new Frame(), true);
                info.jLabel1.setText("Informacion !!!");
                info.textos.setText("Verifique los datos");
                info.setVisible(true);
     //   JOptionPane.showMessageDialog(null, "Verifique sus datos");
        }else{
        //validar email
      if (mather.find() == true) {
       // JOptionPane.showMessageDialog(null,"El email ingresado es válido.");
        Information info  = new Information(new Frame(), true);
                info.jLabel1.setText("Informacion !!!");
                info.textos.setText("El email no es valido");
                info.setVisible(true);
        
        } else {
        int cuentaFilasSeleccionadas = tablaProveedores.getSelectedRowCount();
        if (cuentaFilasSeleccionadas == 1) { 
         //funcion actualizar
             bdprv.actualizarProveedor(proveedorselecionado, nombre, telefono, email,direccion);
             ///funcion actualiza
             //mostra alert
             Success suc = new Success(new JFrame(),true );
                       suc.titulos.setText("!HECHO¡");
                       suc.textos.setText("SE HAN GUARDADO LOS CAMBIOS");
                      suc.setVisible(true);
//-->
        //<---- limpiar
            limpiar();
            //--->
            //<---cargardatosatabla
            CargarModeloTabla();
           //--->     
        }else if(cuentaFilasSeleccionadas == 0){
        //<---mandar parametros   
        CProveedores prove = new CProveedores(0,nombre,"","",direccion,telefono,email);
        //---->
        //<--- fincion registrar
        bdprv.registrar_Proveedor(prove);
        //--->
        //<---Mostrar alert
            Success suc = new Success(new JFrame(),true );
             suc.titulos.setText("!HECHO¡");
             suc.textos.setText("SE HAN ACTUALIZADO LOS DATOS");
            suc.setVisible(true);
            //---->
        //<----cargarmodelo
            CargarModeloTabla();
            ///---->
            ///<----Funcion limpiar
        limpiar();
//---->       
        }
        }
               }    
    } catch (SQLException ex) {
        Logger.getLogger(pnlproveedores.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnagregarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
 try {
            
             int cuentaFilasSeleccionadas = tablaProveedores.getSelectedRowCount();
            if (cuentaFilasSeleccionadas == 0) {
             // JOptionPane.showMessageDialog(null, "Debe serleccionar alguna fila");
                Information info  = new Information(new Frame(), true);
                info.jLabel1.setText("Informacion !!!");
                info.textos.setText("Debe seleccionar alguna fila");
                info.setVisible(true);
            }else{
                //<--- funcion eiminar
                bdprv.EliminiarProveedor(proveedorselecionado);
                //--->
                //<----llamar alert
               Warning warning = new Warning(new Frame(),true);
                warning.jLabel1.setText("Advertencia!!!");
                warning.textos.setText("Esta seguro que deseas eliminar ?");
                warning.setVisible(true);
                     String dato = warning.valor.toString();
                      System.out.println(dato);  
                        if (dato.equals("Aceptar")) {
 ///---->
///limpiar 
                 limpiar();///->>>
                 ///cargardatos a tabla
                CargarModeloTabla();///->>>
                        }
                        
                 Information info  = new Information(new Frame(), true);
                info.jLabel1.setText("Informacion !!!");
                info.textos.setText("Proveedor Eliminado");
                info.setVisible(true);
            }
            
          
        } catch (SQLException ex) {
            Logger.getLogger(pnlUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btneliminarActionPerformed

    private void txtbusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbusquedaKeyTyped
 txtbusqueda.addKeyListener(new KeyAdapter() {
            public void keyReleased(final KeyEvent e) {
                String cadena = (txtbusqueda.getText());
                txtbusqueda.setText(cadena);
                repaint();
                filtroBusqueda(txtbusqueda);
            }
        });
        trsFiltro = new TableRowSorter(tablaProveedores.getModel());
        tablaProveedores.setRowSorter(trsFiltro);        // TODO add your handling code here:
    }//GEN-LAST:event_txtbusquedaKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
limpiar();
tablaProveedores.clearSelection ();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bUSCAR;
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private LIB.JPanelRound jPanelRound1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaProveedores;
    private javax.swing.JTextField txtbusqueda;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
