/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import Alerts.ErrorAlert;
import Alerts.Information;
import Alerts.Success;
import Alerts.SuccessAlert;
import Alerts.Warning;
import Alerts.WarningAlert;
import BD.Proveedores;
import Controller.CProveedores;
import Controller.CUsuarios;
import java.awt.Frame;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author najera10
 */
public class pnlproveedores extends javax.swing.JInternalFrame {
    private TableRowSorter trsFiltro;
     
DefaultTableModel modelotablaProveedores = new DefaultTableModel(){

  public boolean isCellEditable(int filas, int columnas){
            if(columnas==4){
                return true;
            }else{
                return false;
            }
    }


};
Proveedores  bdprv = new Proveedores();
CProveedores  proveedorselecionado = null ;

    public pnlproveedores() {
        initComponents();
        CargarColunmas();
        CargarModeloTabla();
    }
    
        private  void CargarColunmas(){
        modelotablaProveedores.addColumn("Nombre");
        modelotablaProveedores.addColumn("Dirección");
        modelotablaProveedores.addColumn("Telefono");
        modelotablaProveedores.addColumn("Email");
    }

    public void CargarModeloTabla(){
      
       limpiarTabla();
       ArrayList<CProveedores>ListarProveedores = bdprv.ObtenerProveedores();
      int numerosProveedpres = ListarProveedores.size();
      modelotablaProveedores.setNumRows(numerosProveedpres);
        for (int i = 0; i < numerosProveedpres; i++) {
            CProveedores proveedor = ListarProveedores.get(i);
            String nombre = proveedor.getNombre();
            String email = proveedor.getEmail();
            String direccion = proveedor.getDireccion();
            String telefono = proveedor.getTelefono();        
            modelotablaProveedores.setValueAt(proveedor, i, 0);
            modelotablaProveedores.setValueAt(direccion, i, 1);
            modelotablaProveedores.setValueAt(telefono, i, 2);
            modelotablaProveedores.setValueAt(email, i, 3);
        }
         
    }
    
 public void filtroBusqueda(JTextField txt) {
        trsFiltro.setRowFilter(RowFilter.regexFilter(txt.getText()));
 }

    public void limpiar(){
        txtnombre.setText("");
        txtdireccion.setText("");
        txttelefono.setText("");
        txtemail.setText("");
    }
        public  void limpiarTabla(){
        int numFilas = modelotablaProveedores.getRowCount();
        if(numFilas > 0){
            for(int i = numFilas - 1; i >= 0; i--){
                modelotablaProveedores.removeRow(i);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bUSCAR = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProveedores = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanelRound1 = new LIB.JPanelRound();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnagregar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtnombre = new rojeru_san.rsfield.RSTextFull();
        txtdireccion = new rojeru_san.rsfield.RSTextFull();
        txttelefono = new rojeru_san.rsfield.RSTextFull();
        txtemail = new rojeru_san.rsfield.RSTextFull();
        txtbusqueda = new rojeru_san.rsfield.RSTextFull();

        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bUSCAR.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bUSCAR.setText("Buscar:");
        jPanel1.add(bUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 50, 30));

        tablaProveedores.setModel(modelotablaProveedores);
        tablaProveedores.setRowHeight(25);
        tablaProveedores.setRowMargin(0);
        tablaProveedores.setSelectionBackground(new java.awt.Color(102, 153, 255));
        tablaProveedores.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaProveedores.getSelectionModel().addListSelectionListener(
            new ListSelectionListener(){
                public void valueChanged(ListSelectionEvent event){
                    if(!event.getValueIsAdjusting() && (tablaProveedores.getSelectedRow()>= 0) ){
                        int filaseleccionada = tablaProveedores.getSelectedRow();
                        CProveedores proveedor = (CProveedores) modelotablaProveedores.getValueAt(filaseleccionada, 0);
                        txtnombre.setText(proveedor.getNombre());
                        txtdireccion.setText(proveedor.getDireccion());
                        txtemail.setText(proveedor.getEmail());
                        txttelefono.setText(proveedor.getTelefono());
                        proveedorselecionado = proveedor;

                    }
                }
            }   
        );
        jScrollPane1.setViewportView(tablaProveedores);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 1070, 230));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(128, 128, 131));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/fundraiser.png"))); // NOI18N
        jLabel7.setText("PROVEEDORES");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 520, 110));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Listado de Proveedores");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 210, -1));

        jPanelRound1.setBackground(new java.awt.Color(255, 255, 255));
        jPanelRound1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        jPanelRound1.setOpaque(true);
        jPanelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Registro de Proveedor");
        jPanelRound1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 210, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Nombre *");
        jPanelRound1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Direccion*");
        jPanelRound1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Telenono *");
        jPanelRound1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 80, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Email *");
        jPanelRound1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 50, 30));

        btnagregar.setBackground(new java.awt.Color(102, 166, 54));
        btnagregar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/diskette.png"))); // NOI18N
        btnagregar.setMnemonic('g');
        btnagregar.setText("Agregar");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });
        jPanelRound1.add(btnagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 120, 40));

        btneliminar.setBackground(new java.awt.Color(247, 94, 24));
        btneliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/garbage.png"))); // NOI18N
        btneliminar.setMnemonic('e');
        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        jPanelRound1.add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 110, 40));

        jButton1.setBackground(new java.awt.Color(81, 161, 194));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/brush.png"))); // NOI18N
        jButton1.setMnemonic('c');
        jButton1.setText("limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelRound1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 120, 40));

        txtnombre.setForeground(new java.awt.Color(0, 0, 0));
        txtnombre.setBordeColorFocus(new java.awt.Color(153, 153, 255));
        txtnombre.setBotonColor(new java.awt.Color(255, 102, 102));
        txtnombre.setMayusculas(true);
        txtnombre.setPlaceholder("Proveedor");
        jPanelRound1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        txtdireccion.setForeground(new java.awt.Color(0, 0, 0));
        txtdireccion.setBordeColorFocus(new java.awt.Color(153, 153, 255));
        txtdireccion.setBotonColor(new java.awt.Color(255, 102, 102));
        txtdireccion.setMayusculas(true);
        txtdireccion.setPlaceholder("Direccion");
        jPanelRound1.add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 330, -1));

        txttelefono.setForeground(new java.awt.Color(0, 0, 0));
        txttelefono.setBordeColorFocus(new java.awt.Color(153, 153, 255));
        txttelefono.setBotonColor(new java.awt.Color(255, 102, 102));
        txttelefono.setPlaceholder("Telefono");
        txttelefono.setSoloNumeros(true);
        jPanelRound1.add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        txtemail.setForeground(new java.awt.Color(0, 0, 0));
        txtemail.setBordeColorFocus(new java.awt.Color(153, 153, 255));
        txtemail.setBotonColor(new java.awt.Color(255, 102, 102));
        txtemail.setMayusculas(true);
        txtemail.setPlaceholder("Email");
        jPanelRound1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        jPanel1.add(jPanelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 430, 320));

        txtbusqueda.setMayusculas(true);
        txtbusqueda.setPlaceholder("Buscar");
        txtbusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbusquedaKeyReleased(evt);
            }
        });
        jPanel1.add(txtbusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1090, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
    try {
        String nombre = txtnombre.getText();
        String telefono = txttelefono.getText();
        String email = txtemail.getText();
        String  direccion = txtdireccion.getText(); 
   
        if (nombre.equals("") || telefono.equals("") || email.equals("") || direccion.equals("")){
            ErrorAlert e = new ErrorAlert(new JFrame(), true);
            e.msj1.setText("HAY UN PLOBLEMA ");
            e.msj2.setText("VERIFIQUE SUS DATOS");
            e.msj3.setText("");
            e.setVisible(true);

     //   JOptionPane.showMessageDialog(null, "Verifique sus datos");
        }else{
        //validar email
  
        int cuentaFilasSeleccionadas = tablaProveedores.getSelectedRowCount();
        if (cuentaFilasSeleccionadas == 1) { 
         //funcion actualizar
             bdprv.actualizarProveedor(proveedorselecionado, nombre, telefono, email,direccion);
             ///funcion actualiza
             //mostra alert
             SuccessAlert suc = new SuccessAlert(new JFrame(),true );
                       suc.msj1.setText("!HECHO¡");
                       suc.msj2.setText("SE HAN GUARDADO LOS CAMBIOS");
                       suc.msj3.setText("");
                       suc.setVisible(true);
//-->
        //<---- limpiar
            limpiar();
            //--->
            //<---cargardatosatabla
            CargarModeloTabla();
           //--->     
        }else if(cuentaFilasSeleccionadas == 0){
        //<---mandar parametros   
        CProveedores prove = new CProveedores(0,nombre,"","",direccion,telefono,email);
        //---->
        //<--- fincion registrar
        bdprv.registrar_Proveedor(prove);
        //--->
        //<---Mostrar alert
              SuccessAlert suc = new SuccessAlert(new JFrame(),true );
                       suc.msj1.setText("!HECHO¡");
                       suc.msj2.setText("SE HAN ACTUALIZADO LOS DATOS");
                       suc.msj3.setText("");
                       suc.setVisible(true);
            //---->
        //<----cargarmodelo
            CargarModeloTabla();
            ///---->
            ///<----Funcion limpiar
        limpiar();
//---->       
        }
        
               }    
    } catch (SQLException ex) {
        Logger.getLogger(pnlproveedores.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnagregarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
 try {
            
             int cuentaFilasSeleccionadas = tablaProveedores.getSelectedRowCount();
            if (cuentaFilasSeleccionadas == 0) {
             // JOptionPane.showMessageDialog(null, "Debe serleccionar alguna fila");
              ErrorAlert e = new ErrorAlert(new JFrame(), true);
            e.msj1.setText("HAY UN PLOBLEMA ");
            e.msj2.setText("DEBE SELECCIONAR UNA FILA");
            e.msj3.setText("");
            e.setVisible(true);

            }else{
                //<--- funcion eiminar
                bdprv.EliminiarProveedor(proveedorselecionado);
                //--->
                //<----llamar alert
              
                WarningAlert w = new WarningAlert(new JFrame(), true);
                w.msj1.setText("ESTAS SEGURO°°°");
                w.msj2.setText("¡DESEAS ELIMINARLO?");
                w.msj3.setText("");
                w.setVisible(true);

                        if (w.hecho) {
 ///---->
///limpiar 
                 limpiar();///->>>
                 ///cargardatos a tabla
                CargarModeloTabla();///->>>
                 SuccessAlert succ  = new SuccessAlert(new Frame(), true);
                succ.msj1.setText("CORRECTO !!!");
                succ.msj2.setText("SE HA ELIMINADO");
                succ.msj3.setText("");
                succ.setVisible(true);
            }
            
            
            
            }
                        
                
            
          
        } catch (SQLException ex) {
            Logger.getLogger(pnlUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btneliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
limpiar();
tablaProveedores.clearSelection ();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtbusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbusquedaKeyReleased
        limpiarTabla();
       String criterio = txtbusqueda.getText();
       ArrayList<CProveedores>ListarProveedores = bdprv.ObtenerProveedoresporCriterio(criterio);
      int numerosProveedpres = ListarProveedores.size();
      modelotablaProveedores.setNumRows(numerosProveedpres);
        for (int i = 0; i < numerosProveedpres; i++) {
            CProveedores proveedor = ListarProveedores.get(i);
            String nombre = proveedor.getNombre();
            String email = proveedor.getEmail();
            String direccion = proveedor.getDireccion();
            String telefono = proveedor.getTelefono();        
            modelotablaProveedores.setValueAt(proveedor, i, 0);
            modelotablaProveedores.setValueAt(direccion, i, 1);
            modelotablaProveedores.setValueAt(telefono, i, 2);
            modelotablaProveedores.setValueAt(email, i, 3);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtbusquedaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bUSCAR;
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private LIB.JPanelRound jPanelRound1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaProveedores;
    private rojeru_san.rsfield.RSTextFull txtbusqueda;
    private rojeru_san.rsfield.RSTextFull txtdireccion;
    private rojeru_san.rsfield.RSTextFull txtemail;
    private rojeru_san.rsfield.RSTextFull txtnombre;
    private rojeru_san.rsfield.RSTextFull txttelefono;
    // End of variables declaration//GEN-END:variables
}
