/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import Alerts.ErrorAlert;
import Alerts.WarningBackup;
import Alerts.WarningRestore;
import Alerts.Backup;
import BD.configurarTicket;
import Conexion.Conexion;
import Controller.CCTicket;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.PrintService;
import javax.print.PrintServiceLookup;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import modal.CambiarContrasena;
import modal.CambiarUsuario;
import modal.CargandoRestore;
import necesario.RSFileChooser;
import principal.Principal;
import Alerts.Backup;
import java.sql.ResultSet;
import java.sql.Statement;
import org.h2.jdbcx.JdbcDataSource;
import org.h2.tools.Restore;

import principal.Session;

/**
 *
 * @author Najera10
 */
public class pnlRespaldos extends javax.swing.JPanel {

 
       
       
    public pnlRespaldos() {
        initComponents();
       
    }
    
   
    
//
    
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnBackup = new rojeru_san.rsbutton.RSButtonMetro();

        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setBackground(new java.awt.Color(204, 204, 204));
        jLabel16.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Utileria");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 70));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/descargar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 80, 70));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/subir-archivo.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 70, -1));

        btnBackup.setBackground(new java.awt.Color(69, 87, 252));
        btnBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackupActionPerformed(evt);
            }
        });
        add(btnBackup, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            
       GeneraBackup();
               
          
          
        
       

    }//GEN-LAST:event_jButton1ActionPerformed
    public static File existe = null;
    public static File destino = new File("_/");
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      Connection conn = null;
      Statement stmt = null;

      try
      {
          
         System.out.println("Restoring test");
         Restore.execute("D:\\Archivos\\STI\\RespaldoDefinitivo\\Dashboard_1\\respaldos\\sdasa_11-12-2020.zip", "file:./base/", "PuntoVenta");

         JdbcDataSource datasource = new JdbcDataSource();
         datasource.setUrl("jdbc:h2:file:./base/PuntoVenta;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE");
         conn = datasource.getConnection("sa", "admin");
         stmt = conn.createStatement();

        
      } catch (SQLException ex) {     
            Logger.getLogger(pnlRespaldos.class.getName()).log(Level.SEVERE, null, ex);
        }     

        
               
//              
//           try {
//               RestoreBackup();
//           } catch (SQLException ex) {
//               Logger.getLogger(pnlRespaldos.class.getName()).log(Level.SEVERE, null, ex);
//           }
//           
        

    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackupActionPerformed
         GeneraBackup();
        
    }//GEN-LAST:event_btnBackupActionPerformed


    private void RestoreBackup() throws SQLException {  
             
     try {
                   
                  String path = System.getProperty("user.dir")+"\\respaldos";
                   File ruta = new File(path);
               RSFileChooser fileChooser = new RSFileChooser();
        fileChooser.setCurrentDirectory(ruta);
//        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos FDB (*.fdb)", "fdb");
        fileChooser.setAcceptAllFileFilterUsed(false);
//        fileChooser.setFileFilter(filter);
        fileChooser.setDialogTitle("SELECCIONAR RESPALDO");
        if (fileChooser.showOpenDialog(this) == RSFileChooser.APPROVE_OPTION) {
            existe = fileChooser.getSelectedFile();
            if (existe.exists()) {

                WarningRestore a = new WarningRestore(new JFrame(), true);
                a.msj1.setText("Has seleccionado un respaldo y la aplicación");
                a.msj2.setText("se reiniciara al terminar de restaurar la");
                a.msj3.setText("Base de Datos. Se recomienda que haga");
                a.msj4.setText("un respaldo antes de continuar.");
                a.lblTipo.setText("Restaurar");
                a.lblTipo.setVisible(false);    
                a.setVisible(true);

                if (a.continuar) {
                        
                        new CargandoRestore(new JFrame(), true).setVisible(true);
                        pr.dispose();
                        new Session().setVisible(true);
 

                }

            } else {
                ErrorAlert a = new ErrorAlert(new JFrame(), true);
                a.msj1.setText("Archivo no encontrado.");
                a.msj2.setText("");
                a.msj3.setText("");
                a.setVisible(true);
            }
        }
            
               Connection connection = Conexion.getConnection();
           
           } catch (SQLException ex) {
               Logger.getLogger(pnlRespaldos.class.getName()).log(Level.SEVERE, null, ex);
           }
            

        
    }
      
    public static Principal pr = null;

    public static void ventana(Principal p) {
        pr = p;
    }
     
     private void GeneraBackup() {
        WarningBackup a = new WarningBackup(new JFrame(), true);
        a.setVisible(true);
        if (a.continuar) {
             new Alerts.Backup().exportDB(a.txtNombre.getText());
            
           
        }
    }
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.rsbutton.RSButtonMetro btnBackup;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel16;
    // End of variables declaration//GEN-END:variables
}
