/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import BD.Categorias;
import javax.swing.JOptionPane;
import Conexion.Conexion;
import Controller.CCategorias;
import com.sun.org.apache.xerces.internal.impl.dtd.models.CMBinOp;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;


import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author RojeruSan
 */
public class pnlReportes extends javax.swing.JPanel {

       private Connection userConn;
       Categorias categoria = new Categorias();
    public pnlReportes() {
        initComponents();
        cbListado.setEnabled(false);
        cbCombo.setEnabled(false);
        panelfechas.setVisible(false);
        chRango.setVisible(false);
        chTodas.setVisible(false);
         cargaItemInventario();
    }

    
      private void cargaItemInventario(){
        cbListado.removeAllItems();
        cbListado.addItem("General");
        cbListado.addItem("Por Categoria");
        cargarModeloCat();
    }
    
    private void cargarVentas(){
       txt01.setText("Ventas por: ");
        cbCombo.removeAllItems();
        cbCombo.addItem("Articulo");
        cbCombo.addItem("Clintes");
        
    } 
    
    private void cargarModeloCat(){
         cbCombo.removeAllItems();
        txt01.setText("Categoria");
            ArrayList<CCategorias> listaCategorias;
        listaCategorias = categoria.ObtenerCategorias();
        cbCombo.addItem(new CCategorias("0", "Selecciona opcion","",1));

        for(CCategorias categoria : listaCategorias){
            cbCombo.addItem(categoria);
        }
    }
      private void muestra(){
        lb_nombre.setVisible(true);
        cbListado.setVisible(true);
        btGenerar.setVisible(true);
        cbCombo.setVisible(true);
        txt01.setVisible(true);
    }
     
    
      private void AccionProducto() throws JRException{
        if(cbListado.getSelectedIndex()==0){
                 try {
                     System.out.println("General");
            userConn=Conexion.getConnection();
            String path = System.getProperty("user.dir")+"/src/reportes/ProductosGeneral.jasper";
            JasperPrint jprint = JasperFillManager.fillReport(path, null,userConn);
            JasperViewer viewer = new JasperViewer(jprint,false);
            viewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            viewer.setVisible(true);
                
                
            } catch (SQLException | JRException ex) {
                Logger.getLogger(pnlReportes.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex);
            }
            }else{
                System.out.println("Categoria");
                try {
                userConn=Conexion.getConnection();
                Map parametro = new HashMap();
                CCategorias categoria = (CCategorias)cbCombo.getSelectedItem();
               int idcat = Integer.parseInt(categoria.getIdcategoria());
                parametro.put("id_cate",idcat);
                String path = System.getProperty("user.dir")+"/src/reportes/ProductosCategorias.jasper";
            JasperPrint jprint = JasperFillManager.fillReport(path, parametro,userConn);
            JasperViewer viewer = new JasperViewer(jprint,false);
            viewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            viewer.setVisible(true);
                
                
            } catch (SQLException ex) {
                Logger.getLogger(pnlReportes.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex);
            }
            }
    }
      
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botongrupo = new javax.swing.ButtonGroup();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JlReportes = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lb_nombre = new javax.swing.JLabel();
        jPanelRound1 = new LIB.JPanelRound();
        cbListado = new javax.swing.JComboBox();
        cbCombo = new javax.swing.JComboBox();
        chTodas = new javax.swing.JRadioButton();
        chRango = new javax.swing.JRadioButton();
        panelfechas = new javax.swing.JPanel();
        jdFfin = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jdFini = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        btGenerar = new javax.swing.JButton();
        txt01 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(128, 128, 131));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("REPORTES");
        add(jLabel7);
        jLabel7.setBounds(290, 40, 330, 100);

        JlReportes.setBackground(new java.awt.Color(240, 240, 240));
        JlReportes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JlReportes.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Clientes", "Usuarios", "Productos", "Proveedores", "Ventas", "Ingresos" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        JlReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JlReportesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JlReportes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        add(jPanel1);
        jPanel1.setBounds(130, 280, 260, 240);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/newspaper (2).png"))); // NOI18N
        add(jLabel4);
        jLabel4.setBounds(90, 30, 160, 140);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Selecciona tipo de Reporte");
        add(jLabel1);
        jLabel1.setBounds(150, 230, 240, 38);

        lb_nombre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_nombre.setText("Reporte");
        add(lb_nombre);
        lb_nombre.setBounds(630, 220, 150, 40);

        jPanelRound1.setBackground(new java.awt.Color(255, 255, 255));
        jPanelRound1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 6, true));
        jPanelRound1.setOpaque(true);

        cbListado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbListadoItemStateChanged(evt);
            }
        });
        cbListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbListadoActionPerformed(evt);
            }
        });

        cbCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbComboActionPerformed(evt);
            }
        });

        botongrupo.add(chTodas);
        chTodas.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        chTodas.setText("Hoy");
        chTodas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chTodasMouseClicked(evt);
            }
        });

        botongrupo.add(chRango);
        chRango.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        chRango.setText("Rango de Fechas");
        chRango.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chRangoMouseClicked(evt);
            }
        });

        jdFfin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jdFfinMouseClicked(evt);
            }
        });

        jLabel3.setText("a");

        jLabel2.setText("De:");

        javax.swing.GroupLayout panelfechasLayout = new javax.swing.GroupLayout(panelfechas);
        panelfechas.setLayout(panelfechasLayout);
        panelfechasLayout.setHorizontalGroup(
            panelfechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelfechasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jdFini, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdFfin, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelfechasLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jdFfin, jdFini});

        panelfechasLayout.setVerticalGroup(
            panelfechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelfechasLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(panelfechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jdFfin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdFini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        btGenerar.setBackground(new java.awt.Color(81, 161, 194));
        btGenerar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btGenerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/report.png"))); // NOI18N
        btGenerar.setText("Generar");
        btGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGenerarActionPerformed(evt);
            }
        });

        txt01.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        txt01.setText("txt01");

        javax.swing.GroupLayout jPanelRound1Layout = new javax.swing.GroupLayout(jPanelRound1);
        jPanelRound1.setLayout(jPanelRound1Layout);
        jPanelRound1Layout.setHorizontalGroup(
            jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRound1Layout.createSequentialGroup()
                .addGroup(jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRound1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelRound1Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(cbListado, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelRound1Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(chTodas)
                                .addGap(35, 35, 35)
                                .addComponent(chRango, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(panelfechas, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelRound1Layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(btGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelRound1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(txt01, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanelRound1Layout.setVerticalGroup(
            jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRound1Layout.createSequentialGroup()
                .addGap(0, 7, Short.MAX_VALUE)
                .addComponent(cbListado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt01, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chTodas)
                    .addComponent(chRango))
                .addGap(17, 17, 17)
                .addComponent(panelfechas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanelRound1);
        jPanelRound1.setBounds(460, 270, 470, 250);
    }// </editor-fold>//GEN-END:initComponents

    private void JlReportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlReportesMouseClicked
            
//            //Reporte clientes
            if(JlReportes.getSelectedValue().equals("Clientes")){
               validar(false);
              lb_nombre.setText((String) JlReportes.getSelectedValue());
        }
        //Reporte de usuarios
        if(JlReportes.getSelectedValue().equals("Usuarios")){
           validar(false);
        lb_nombre.setText((String) JlReportes.getSelectedValue());
            }
        
        //Reporte Productos
          if(JlReportes.getSelectedValue().equals("Productos")){
             validar(false);
        
            cbListado.setEnabled(true);
            lb_nombre.setText((String) JlReportes.getSelectedValue());
           
        }
        //Reporte Proveedores
       if(JlReportes.getSelectedValue().equals("Proveedores")){
            validar(false);
            lb_nombre.setText((String) JlReportes.getSelectedValue());
        }
       //Reporte de ventas       //Reporte de ventas       //Reporte de ventas       //Reporte de ventas
       
        if (JlReportes.getSelectedValue().equals("Ventas")) {
            lb_nombre.setText((String) JlReportes.getSelectedValue());
            validar(true);
         
            
        }
        
        if (JlReportes.getSelectedValue().equals("Ingresos")) {
            lb_nombre.setText((String) JlReportes.getSelectedValue());
            validar(true);
         
            
        }
       
       
       
    }//GEN-LAST:event_JlReportesMouseClicked

    private void cbListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbListadoActionPerformed

    }//GEN-LAST:event_cbListadoActionPerformed

    private void btGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGenerarActionPerformed
        if (lb_nombre.getText().equals("Reporte")) {
            JOptionPane.showMessageDialog(null, "NO HA SELECCIONADO NINGUNA OPCCION");
        }else{
        
        
   if(lb_nombre.getText().equals("Productos")){
    try {
        AccionProducto();
    } catch (JRException ex) {
    }
        }
        if (lb_nombre.getText().equals("Ventas") ){    
        //            String formato ="dd/MM/yyyy";        
        if (chRango.isSelected()==false && chTodas.isSelected()==false) {
           JOptionPane.showMessageDialog(null, "No se ha seleccionado ninguna opcion");
        }else{
//reporte ventas por rango
       if (chRango.isSelected()) {            
    try {
        String formato ="yyyy-MM-dd";
        Date date = jdFini.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat(formato);
        Date date1 = jdFfin.getDate();
        System.out.println(date);
        userConn=Conexion.getConnection();
        Map parametro = new HashMap();
        parametro.put("fechainicio",date);
        parametro.put("fechafin",date1);
        String path = System.getProperty("user.dir")+"/src/reportes/report2.jasper";
        JasperPrint jprint = JasperFillManager.fillReport(path, parametro,userConn);
        JasperViewer viewer = new JasperViewer(jprint,false);
        viewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        viewer.setVisible(true);
    } catch (SQLException ex) {
        Logger.getLogger(pnlReportes.class.getName()).log(Level.SEVERE, null, ex);
    } catch (JRException ex) {
        Logger.getLogger(pnlReportes.class.getName()).log(Level.SEVERE, null, ex);
    }
       } 
       //reporte ventas de hoy 
        if(chTodas.isSelected()){
           
    try {
        //Obtenemos la fecha actual y creamos un objeto Date Sql
        java.util.Date fecha = new Date();
        System.out.println(fecha);
        userConn=Conexion.getConnection();
        Map parametro = new HashMap();
        parametro.put("fechahoy",fecha);
        String path = System.getProperty("user.dir")+"/src/reportes/ReporteVentashoy.jasper";
        JasperPrint jprint = JasperFillManager.fillReport(path, parametro,userConn);
        JasperViewer viewer = new JasperViewer(jprint,false);
        viewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        viewer.setVisible(true);
    } catch (JRException ex) {
        Logger.getLogger(pnlReportes.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
        Logger.getLogger(pnlReportes.class.getName()).log(Level.SEVERE, null, ex);
    }
          
     } 
    }
   }
        
        if(JlReportes.getSelectedValue().equals("Clientes")){
               validar(false);
        
                
                try {
                    JOptionPane.showMessageDialog(null,"PROCESANDO");
                    
                    userConn=Conexion.getConnection();
                    String path = System.getProperty("user.dir")+"/src/reportes/reportesclientes.jasper";
                    JasperPrint jprint = JasperFillManager.fillReport(path, null,userConn);
                    JasperViewer viewer = new JasperViewer(jprint,false);
                    viewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                    viewer.setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(pnlReportes.class.getName()).log(Level.SEVERE, null, ex);
                } catch (JRException ex) {
                    Logger.getLogger(pnlReportes.class.getName()).log(Level.SEVERE, null, ex);
                }
         
        }

        if(JlReportes.getSelectedValue().equals("Usuarios")){
             validar(false);
        
                try {
                    userConn=Conexion.getConnection();
                    String path = System.getProperty("user.dir")+"/src/reportes/reporteusuarios.jasper";
                    JasperPrint jprint = JasperFillManager.fillReport(path, null,userConn);
                    JasperViewer viewer = new JasperViewer(jprint,false);
                    viewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                    viewer.setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(pnlReportes.class.getName()).log(Level.SEVERE, null, ex);
                } catch (JRException ex) {
                    Logger.getLogger(pnlReportes.class.getName()).log(Level.SEVERE, null, ex);
                }
           
            }
        
         //Reporte Productos
  
        
        //Reporte Proveedores
       if(JlReportes.getSelectedValue().equals("Proveedores")){
           validar(false);
          try {
            userConn=Conexion.getConnection();
            String path = System.getProperty("user.dir")+"/src/reportes/ReportedeProveedores.jasper";
            JasperPrint jprint = JasperFillManager.fillReport(path, null,userConn);
            JasperViewer viewer = new JasperViewer(jprint,false);
            viewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            viewer.setVisible(true);         
            } catch (SQLException | JRException ex) {
                Logger.getLogger(pnlReportes.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex);
            }
        }
       
       if(JlReportes.getSelectedValue().equals("Ingresos")){
            if (chRango.isSelected()==false && chTodas.isSelected()==false) {
           JOptionPane.showMessageDialog(null, "No se ha seleccionado ninguna opcion");
        }else{
//reporte ventas por rango
       if (chRango.isSelected()) {            
    try {
        String formato ="yyyy-MM-dd";
        Date inicio = jdFini.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat(formato);
        Date fin = jdFfin.getDate();
        System.out.println(inicio);
        userConn=Conexion.getConnection();
        Map parametro = new HashMap();
        parametro.put("fechainicio",inicio);
        parametro.put("fechafin",fin);
        String path = System.getProperty("user.dir")+"/src/reportes/ReporteIngresosFechas.jasper";
        JasperPrint jprint = JasperFillManager.fillReport(path, parametro,userConn);
        JasperViewer viewer = new JasperViewer(jprint,false);
        viewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        viewer.setVisible(true);
    } catch (SQLException ex) {
        Logger.getLogger(pnlReportes.class.getName()).log(Level.SEVERE, null, ex);
    } catch (JRException ex) {
        Logger.getLogger(pnlReportes.class.getName()).log(Level.SEVERE, null, ex);
    }
       } 
       //reporte ventas de hoy 
        if(chTodas.isSelected()){
           
    try {
        //Obtenemos la fecha actual y creamos un objeto Date Sql
        java.util.Date fechaing = new Date();
        System.out.println(fechaing);
        userConn=Conexion.getConnection();
        Map parametro = new HashMap();
        parametro.put("fechahoy",fechaing);
        String path = System.getProperty("user.dir")+"/src/reportes/ReporteIngresosHoy.jasper";
        JasperPrint jprint = JasperFillManager.fillReport(path, parametro,userConn);
        JasperViewer viewer = new JasperViewer(jprint,false);
        viewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        viewer.setVisible(true);
    } catch (JRException ex) {
        Logger.getLogger(pnlReportes.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
        Logger.getLogger(pnlReportes.class.getName()).log(Level.SEVERE, null, ex);
    }
          
     } 
    }
       }
       
       
        }
    }//GEN-LAST:event_btGenerarActionPerformed

    private void cbComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbComboActionPerformed

    private void jdFfinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jdFfinMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jdFfinMouseClicked

    private void chTodasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chTodasMouseClicked
       
        validar(false);

     
    }//GEN-LAST:event_chTodasMouseClicked

    private void chRangoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chRangoMouseClicked
       
        validar(true);

    }//GEN-LAST:event_chRangoMouseClicked

    private void cbListadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbListadoItemStateChanged
        String categoria1 = (String) cbListado.getSelectedItem();

        if (categoria1.equals("Por Categoria")) {
            cbCombo.setEnabled(true);
        }else{
            cbCombo.setEnabled(false);
        }

// TODO add your handling code here:
    }//GEN-LAST:event_cbListadoItemStateChanged

    public void  validar(boolean bandera){
        if(bandera){
             panelfechas.setVisible(true);
//             chTodas.setSelected(true);
//             chRango.setSelected(true);
             chTodas.setVisible(true);
             chRango.setVisible(true);
             cbListado.setEnabled(false);

        }else{
             panelfechas.setVisible(false);
             chTodas.setSelected(false);
             chRango.setSelected(false);
             chTodas.setVisible(false);
             chRango.setVisible(false);
             cbListado.setEnabled(false);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList JlReportes;
    private javax.swing.ButtonGroup botongrupo;
    private javax.swing.JButton btGenerar;
    private javax.swing.JComboBox cbCombo;
    private javax.swing.JComboBox cbListado;
    private javax.swing.JRadioButton chRango;
    private javax.swing.JRadioButton chTodas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private LIB.JPanelRound jPanelRound1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdFfin;
    private com.toedter.calendar.JDateChooser jdFini;
    private javax.swing.JLabel lb_nombre;
    private javax.swing.JPanel panelfechas;
    private javax.swing.JLabel txt01;
    // End of variables declaration//GEN-END:variables
}
