/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import Alerts.ErrorAlert;
import Alerts.Information;
import Alerts.Success;
import Alerts.SuccessAlert;
import Alerts.Warning;
import Alerts.WarningAlert;
import BD.Usuarios;
import Controller.CPermisos;
import Controller.CUsuarios;
import java.awt.Frame;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import rojerusan.RSNotifyFade;

/**
 *
 * @author RojeruSan
 */
public class pnlUsuarios extends javax.swing.JPanel {
   

    DefaultTableModel modeloTabla = new DefaultTableModel(){
    
      public boolean isCellEditable(int filas, int columnas){
            if(columnas == 4){
                return true;
            }else{
                return false;
            }
    }
    
    };
    CUsuarios  usuarioseleccionado = null ;
    Usuarios  bdusr = new Usuarios();
    private TableRowSorter trsFiltro;
     
     
    public pnlUsuarios() {
        
        initComponents();
        CargarColunmas();
        CargarModeloTabla();
    }
    
    private  void CargarColunmas(){
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Email");
        modeloTabla.addColumn("Usuario");
        modeloTabla.addColumn("Estado");
        
    }

    public void CargarModeloTabla(){
      
       limpiarTabla();
       ArrayList<CUsuarios>ListarUsuarios = bdusr.ObtenerUsuarios();
      int numerosUsusarios = ListarUsuarios.size();
      modeloTabla.setNumRows(numerosUsusarios);
        for (int i = 0; i < numerosUsusarios; i++) {
            CUsuarios usuarios = ListarUsuarios.get(i);
            String nombre = usuarios.getNombre();
            String email = usuarios.getEmail();
            String usuario = usuarios.getLogin();
            String estatus = usuarios.getCodicion();
            
            if(estatus.equals("1")){
                estatus = "Activo";
            }else{
                estatus = "Inactivo";
            }
            modeloTabla.setValueAt(usuarios, i, 0);
            modeloTabla.setValueAt(email, i, 1);
            modeloTabla.setValueAt(usuario, i, 2);
            modeloTabla.setValueAt(estatus, i, 3);
        }
         
    }
    public void filtroBusqueda(JTextField txt) {
        trsFiltro.setRowFilter(RowFilter.regexFilter(txt.getText()));
    }

   
        public  void limpiarTabla(){
        int numFilas = modeloTabla.getRowCount();
        if(numFilas > 0){
            for(int i = numFilas - 1; i >= 0; i--){
                modeloTabla.removeRow(i);
            }
        }
    }
    
     
     
     public void limpiar(){
         txtusuario.setText("");
         txttelefono.setText("");
         txtcorreo.setText("");
         txtnombre.setText("");
         txtcontrasena.setText("");
         txtdireccion.setText("");
         jcpv.setSelected(false);
         jcac.setSelected(false);
         jcal.setSelected(false);
         jcco.setSelected(false);
         jcre.setSelected(false);
         jccl.setSelected(false);
    }
         /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuario = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanelRound1 = new LIB.JPanelRound();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jcpv = new javax.swing.JCheckBox();
        jcal = new javax.swing.JCheckBox();
        jcac = new javax.swing.JCheckBox();
        jcre = new javax.swing.JCheckBox();
        jcco = new javax.swing.JCheckBox();
        jccl = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        btneliminar1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtnombre = new rojeru_san.rsfield.RSTextFull();
        txtcorreo = new rojeru_san.rsfield.RSTextFull();
        txttelefono = new rojeru_san.rsfield.RSTextFull();
        txtusuario = new rojeru_san.rsfield.RSTextFull();
        txtcontrasena = new rojeru_san.rsfield.RSPassword();
        txtdireccion = new rojeru_san.rsfield.RSTextFull();
        jLabel13 = new javax.swing.JLabel();
        txtbusuario = new rojeru_san.rsfield.RSTextFull();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(128, 128, 131));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/group.png"))); // NOI18N
        jLabel7.setText("USUARIOS");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 390, 130));

        tablaUsuario.setModel(modeloTabla);
        tablaUsuario.setFocusable(false);
        tablaUsuario.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tablaUsuario.setRowHeight(25);
        tablaUsuario.setSelectionBackground(new java.awt.Color(232, 57, 95));
        tablaUsuario.setShowVerticalLines(false);
        tablaUsuario.getTableHeader().setReorderingAllowed(false);
        tablaUsuario.getSelectionModel().addListSelectionListener(
            new ListSelectionListener(){
                public void valueChanged(ListSelectionEvent event){
                    if(!event.getValueIsAdjusting() && (tablaUsuario.getSelectedRow()>= 0) ){
                        int filaseleccionada = tablaUsuario.getSelectedRow();
                        CUsuarios usuario = (CUsuarios) modeloTabla.getValueAt(filaseleccionada, 0);
                        txtnombre.setText(usuario.getNombre());
                        txttelefono.setText(usuario.getTelefono());
                        txtcorreo.setText(usuario.getEmail());
                        txtusuario.setText(usuario.getLogin());
                        txtcontrasena.setText(usuario.getClave());
                        txtdireccion.setText(usuario.getDireccion());
                        usuarioseleccionado = usuario;

                        Usuarios user = new Usuarios();
                        try{
                            ArrayList<Object> listarPermisos;
                            listarPermisos = user.obtenerpermiosos(usuario.getId_usuario());

                            System.out.println(listarPermisos);

                            if (listarPermisos.contains(1)) {
                                jcpv.setSelected(true);
                            }else{
                                jcpv.setSelected(false);
                            }
                            if (listarPermisos.contains(2)) {
                                jcal.setSelected(true);
                            }else{
                                jcal.setSelected(false);
                            }
                            if (listarPermisos.contains(4)) {
                                jccl.setSelected(true);
                            }else{
                                jccl.setSelected(false);
                            }
                            if (listarPermisos.contains(5)) {
                                jcac.setSelected(true);
                            }else{
                                jcac.setSelected(false);
                            }
                            if (listarPermisos.contains(3)) {
                                jcco.setSelected(true);
                            }else{
                                jcco.setSelected(false);
                            }
                            if (listarPermisos.contains(6)) {
                                jcre.setSelected(true);
                            }else{
                                jcre.setSelected(false);
                            }

                        }catch (SQLException ex) {
                            JOptionPane.showMessageDialog(null, ex, "Error de conexión", JOptionPane.ERROR_MESSAGE);

                        }

                    }
                }
            }   
        );

        jScrollPane1.setViewportView(tablaUsuario);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 1040, 230));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Buscar:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jPanelRound1.setBackground(new java.awt.Color(255, 255, 255));
        jPanelRound1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        jPanelRound1.setOpaque(true);
        jPanelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setText("Datos de Usuario");
        jPanelRound1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Nombre:");
        jPanelRound1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 60, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Telefono:");
        jPanelRound1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 70, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Contraseña:");
        jPanelRound1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 80, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Usuario:");
        jPanelRound1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 60, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Email:");
        jPanelRound1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 60, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Dirección:");
        jPanelRound1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 70, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Permisos.");
        jPanelRound1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jcpv.setBackground(new java.awt.Color(255, 255, 255));
        jcpv.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jcpv.setText("Punto de Venta");
        jPanelRound1.add(jcpv, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        jcal.setBackground(new java.awt.Color(255, 255, 255));
        jcal.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jcal.setText("Almacen");
        jPanelRound1.add(jcal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, -1, -1));

        jcac.setBackground(new java.awt.Color(255, 255, 255));
        jcac.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jcac.setText("Acceso");
        jPanelRound1.add(jcac, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        jcre.setBackground(new java.awt.Color(255, 255, 255));
        jcre.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jcre.setText("Reportes");
        jPanelRound1.add(jcre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, -1, -1));

        jcco.setBackground(new java.awt.Color(255, 255, 255));
        jcco.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jcco.setText("Compras");
        jPanelRound1.add(jcco, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, -1, -1));

        jccl.setBackground(new java.awt.Color(255, 255, 255));
        jccl.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jccl.setText("Clientes");
        jPanelRound1.add(jccl, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        jButton1.setBackground(new java.awt.Color(102, 166, 54));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/diskette.png"))); // NOI18N
        jButton1.setMnemonic('g');
        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelRound1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 160, 40));

        btneliminar1.setBackground(new java.awt.Color(247, 94, 24));
        btneliminar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btneliminar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/garbage.png"))); // NOI18N
        btneliminar1.setMnemonic('e');
        btneliminar1.setText("Eliminar");
        btneliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminar1ActionPerformed(evt);
            }
        });
        jPanelRound1.add(btneliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 160, 40));

        jButton2.setBackground(new java.awt.Color(81, 161, 194));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/brush.png"))); // NOI18N
        jButton2.setMnemonic('c');
        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanelRound1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 160, 40));

        txtnombre.setForeground(new java.awt.Color(0, 0, 0));
        txtnombre.setBordeColorFocus(new java.awt.Color(153, 153, 255));
        txtnombre.setBotonColor(new java.awt.Color(255, 102, 102));
        txtnombre.setMayusculas(true);
        txtnombre.setPlaceholder("Nombre");
        jPanelRound1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 530, -1));

        txtcorreo.setForeground(new java.awt.Color(0, 0, 0));
        txtcorreo.setBordeColorFocus(new java.awt.Color(153, 153, 255));
        txtcorreo.setBotonColor(new java.awt.Color(255, 102, 102));
        txtcorreo.setMayusculas(true);
        txtcorreo.setPlaceholder("Email");
        jPanelRound1.add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        txttelefono.setForeground(new java.awt.Color(0, 0, 0));
        txttelefono.setBordeColorFocus(new java.awt.Color(153, 153, 255));
        txttelefono.setBotonColor(new java.awt.Color(255, 102, 102));
        txttelefono.setPlaceholder("Telefono");
        txttelefono.setSoloNumeros(true);
        jPanelRound1.add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 190, -1));

        txtusuario.setForeground(new java.awt.Color(0, 0, 0));
        txtusuario.setBordeColorFocus(new java.awt.Color(153, 153, 255));
        txtusuario.setBotonColor(new java.awt.Color(255, 102, 102));
        txtusuario.setMayusculas(true);
        txtusuario.setPlaceholder("Usuario");
        jPanelRound1.add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        txtcontrasena.setForeground(new java.awt.Color(0, 0, 0));
        txtcontrasena.setBordeColorFocus(new java.awt.Color(153, 153, 255));
        jPanelRound1.add(txtcontrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 190, -1));

        txtdireccion.setForeground(new java.awt.Color(0, 0, 0));
        txtdireccion.setBordeColorFocus(new java.awt.Color(153, 153, 255));
        txtdireccion.setBotonColor(new java.awt.Color(255, 102, 102));
        txtdireccion.setMayusculas(true);
        txtdireccion.setPlaceholder("Direccion");
        jPanelRound1.add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 530, 40));

        add(jPanelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 630, 360));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setText("Listado de Productos");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, 34));

        txtbusuario.setForeground(new java.awt.Color(0, 0, 0));
        txtbusuario.setMayusculas(true);
        txtbusuario.setPlaceholder("Buscar");
        txtbusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbusuarioActionPerformed(evt);
            }
        });
        txtbusuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbusuarioKeyReleased(evt);
            }
        });
        add(txtbusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

     
        
        if(jcpv.isSelected() || jcal.isSelected() || jcco.isSelected() || jccl.isSelected()||jcac.isSelected()||jcre.isSelected()){
         
            ArrayList<Object> ListarCheck = new ArrayList<Object>();
       
        int permisos = 0;
        if (jcpv.isSelected()) {
            permisos = 1;
            ListarCheck.add(permisos);
        }
        if (jcal.isSelected()) {
            permisos= 2;
            ListarCheck.add(permisos);
        }
        if (jcco.isSelected()) {
            permisos = 3;
            ListarCheck.add(permisos);
        }
        if (jccl.isSelected()) {
            permisos = 4;
            ListarCheck.add(permisos);
        }
        if (jcac.isSelected()) {
            permisos = 5;
            ListarCheck.add(permisos);
        }
        if (jcre.isSelected()) {
            permisos = 6;
            ListarCheck.add(permisos);
        }
       
       
        
          try {
           
            
            
            String nombre = txtnombre.getText();
            String telefono = txttelefono.getText();
            String email = txtcorreo.getText();
            String cargo ="USER";
            String usuario = txtusuario.getText();
            String contraseña = txtcontrasena.getText();
            String  direccion = txtdireccion.getText();
           
            int cuentaFilasSeleccionadas = tablaUsuario.getSelectedRowCount(); 
           

        if (cuentaFilasSeleccionadas == 1) {    
//      bdusr.actualizarUsuario(usuarioseleccionado, nombre, telefono, usuario, contraseña, direccion);
        bdusr.actualizarUsuario(usuarioseleccionado, nombre, direccion, telefono, email, usuario, contraseña);
        
        
        
       bdusr.eliminarPermisos(usuarioseleccionado);
       bdusr.actualizarPermisos(ListarCheck, usuarioseleccionado);
         SuccessAlert suc = new SuccessAlert(new JFrame(),true );
                       suc.msj1.setText("!HECHO¡");
                       suc.msj2.setText("SE HAN ACTUALIZADO LOS DATOS");
                       suc.msj3.setText("");
                       suc.setVisible(true);
        limpiar();
        CargarModeloTabla();
        } else if (cuentaFilasSeleccionadas == 0 ) { 
        CUsuarios usuarios  = new CUsuarios(0,nombre,"","",direccion,telefono,email,cargo,usuario,contraseña,"", "1");
        Long iduser = bdusr.insert(usuarios);  
        bdusr.guardarPermisos(ListarCheck,iduser);
         SuccessAlert suc = new SuccessAlert(new JFrame(),true );
                       suc.msj1.setText("!HECHO¡");
                       suc.msj2.setText("SE HAN GUARDADO LOS CAMBIOS");
                       suc.msj3.setText("");
                       suc.setVisible(true);
        //new RSNotifyFade("!Alerta!", "Usuario Registrado", 5, RSNotifyFade.PositionNotify.TopRight, RSNotifyFade.TypeNotify.SUCCESS).setVisible(true);
        CargarModeloTabla();
        limpiar();
        }
        } catch (SQLException ex) {
            Logger.getLogger(pnlUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }   
        }else{
          // JOptionPane.showMessageDialog(null,"No hay ningun Permiso marcado");
            ErrorAlert e = new ErrorAlert(new JFrame(), true);
            e.msj1.setText("HAY UN PLOBLEMA ");
            e.msj2.setText("NO HAY NINGUN PERMISO MARCADO");
            e.msj3.setText("");
            e.setVisible(true);

    }
       
    

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btneliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminar1ActionPerformed
         try {
            
             int cuentaFilasSeleccionadas = tablaUsuario.getSelectedRowCount();
            if (cuentaFilasSeleccionadas == 0) {
                ErrorAlert e = new ErrorAlert(new JFrame(), true);
                e.msj1.setText("HAY UN PLOBLEMA ");
                e.msj2.setText("DEBE SELECCIONAR UN FILA");
                e.msj3.setText("");
                e.setVisible(true);
               
            }else{
                  WarningAlert w = new WarningAlert(new JFrame(), true);
                w.msj1.setText("ESTAS SEGURO°°°");
                w.msj2.setText("¡DESEAS ELIMINARLO?");
                w.msj3.setText("");
                w.setVisible(true);
                      
                 if (w.hecho) {
                bdusr.eliminarusuario(usuarioseleccionado);
                limpiar();
                CargarModeloTabla();
               
                  SuccessAlert succ  = new SuccessAlert(new Frame(), true);
                succ.msj1.setText("CORRECTO !!!");
                succ.msj2.setText("SE HA ELIMINADO EL USUARIO");
                succ.msj3.setText("");
                succ.setVisible(true);
                
            }
              
           
            }
        } catch (SQLException ex) {
            Logger.getLogger(pnlUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btneliminar1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
limpiar();     
tablaUsuario.clearSelection ();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtbusuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbusuarioKeyReleased
        limpiarTabla();
            String criterio = txtbusuario.getText();
            
       ArrayList<CUsuarios>ListarUsuarios = bdusr.ObtenerUsuariospotCriterio(criterio);
      int numerosUsusarios = ListarUsuarios.size();
      modeloTabla.setNumRows(numerosUsusarios);
        for (int i = 0; i < numerosUsusarios; i++) {
            CUsuarios usuarios = ListarUsuarios.get(i);
            String nombre = usuarios.getNombre();
            String email = usuarios.getEmail();
            String usuario = usuarios.getLogin();
            String estatus = usuarios.getCodicion();
            
            if(estatus.equals("1")){
                estatus = "ACTIVO";
            }else{
                estatus = "INACTIVO";
            }
            modeloTabla.setValueAt(usuarios, i, 0);
            modeloTabla.setValueAt(email, i, 1);
            modeloTabla.setValueAt(usuario, i, 2);
            modeloTabla.setValueAt(estatus, i, 3);
        }         // TODO add your handling code here:
    }//GEN-LAST:event_txtbusuarioKeyReleased

    private void txtbusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbusuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btneliminar1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private LIB.JPanelRound jPanelRound1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox jcac;
    private javax.swing.JCheckBox jcal;
    private javax.swing.JCheckBox jccl;
    private javax.swing.JCheckBox jcco;
    private javax.swing.JCheckBox jcpv;
    private javax.swing.JCheckBox jcre;
    public javax.swing.JTable tablaUsuario;
    private rojeru_san.rsfield.RSTextFull txtbusuario;
    private rojeru_san.rsfield.RSPassword txtcontrasena;
    private rojeru_san.rsfield.RSTextFull txtcorreo;
    private rojeru_san.rsfield.RSTextFull txtdireccion;
    private rojeru_san.rsfield.RSTextFull txtnombre;
    private rojeru_san.rsfield.RSTextFull txttelefono;
    private rojeru_san.rsfield.RSTextFull txtusuario;
    // End of variables declaration//GEN-END:variables

   
}
